//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace TidyChat.Localization.Resources {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages_ploc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages_ploc() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TidyChat.Localization.Resources.Languages.ploc", typeof(Languages_ploc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AdvancedTab_ChatHistoryTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_ChatHistoryTabHeader", resourceCulture);
            }
        }
        
        internal static string AdvancedTab_CraftingGatheringTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_CraftingGatheringTabHeader", resourceCulture);
            }
        }
        
        internal static string AdvancedTab_EnableDebugMode {
            get {
                return ResourceManager.GetString("AdvancedTab_EnableDebugMode", resourceCulture);
            }
        }
        
        internal static string AdvancedTab_LootObtainTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_LootObtainTabHeader", resourceCulture);
            }
        }
        
        internal static string AdvancedTab_ProgressTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_ProgressTabHeader", resourceCulture);
            }
        }
        
        internal static string AdvancedTab_SystemTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_SystemTabHeader", resourceCulture);
            }
        }
        
        internal static string AdvancedTab_WhitelistTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_WhitelistTabHeader", resourceCulture);
            }
        }
        
        internal static string BetterStrings_CommendationsFromCompletingDuty {
            get {
                return ResourceManager.GetString("BetterStrings_CommendationsFromCompletingDuty", resourceCulture);
            }
        }
        
        internal static string BetterStrings_CommendationSingular {
            get {
                return ResourceManager.GetString("BetterStrings_CommendationSingular", resourceCulture);
            }
        }
        
        internal static string BetterStrings_CommendationsPlural {
            get {
                return ResourceManager.GetString("BetterStrings_CommendationsPlural", resourceCulture);
            }
        }
        
        internal static string BetterStrings_ReceivedCommendationsMessages {
            get {
                return ResourceManager.GetString("BetterStrings_ReceivedCommendationsMessages", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_ChatHistoryTimer {
            get {
                return ResourceManager.GetString("ChatHistoryTab_ChatHistoryTimer", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_ChatHistoryTimerHelpMarker {
            get {
                return ResourceManager.GetString("ChatHistoryTab_ChatHistoryTimerHelpMarker", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_CraftingChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_CraftingChannel", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_EmotesChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_EmotesChannel", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_EnableChatHistoryFilter {
            get {
                return ResourceManager.GetString("ChatHistoryTab_EnableChatHistoryFilter", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_EnableChatHistoryFilterHelpMarker {
            get {
                return ResourceManager.GetString("ChatHistoryTab_EnableChatHistoryFilterHelpMarker", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_GatheringChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_GatheringChannel", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_IgnoreMessagesSentByPlayer {
            get {
                return ResourceManager.GetString("ChatHistoryTab_IgnoreMessagesSentByPlayer", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_IgnoreMessagesSentByPlayerHelpMarker {
            get {
                return ResourceManager.GetString("ChatHistoryTab_IgnoreMessagesSentByPlayerHelpMarker", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_LengthOfChatHistory {
            get {
                return ResourceManager.GetString("ChatHistoryTab_LengthOfChatHistory", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_LengthOfChatHistoryWarningMessage {
            get {
                return ResourceManager.GetString("ChatHistoryTab_LengthOfChatHistoryWarningMessage", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_LoginLogoutChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_LoginLogoutChannel", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_LootChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_LootChannel", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_ProgressChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_ProgressChannel", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_SelectChannels {
            get {
                return ResourceManager.GetString("ChatHistoryTab_SelectChannels", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_SystemChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_SystemChannel", resourceCulture);
            }
        }
        
        internal static string ChatHistoryTab_TalkingChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_TalkingChannel", resourceCulture);
            }
        }
        
        internal static string ConfigWindow_AdvancedSettingsTabHeader {
            get {
                return ResourceManager.GetString("ConfigWindow_AdvancedSettingsTabHeader", resourceCulture);
            }
        }
        
        internal static string ConfigWindow_SettingsTabHeader {
            get {
                return ResourceManager.GetString("ConfigWindow_SettingsTabHeader", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_CraftingDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_CraftingDropdownHeader", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_DesynthesisDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_DesynthesisDropdownHeader", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_FishingDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_FishingDropdownHeader", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_GatheringLocationsDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_GatheringLocationsDropdownHeader", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_HideGatheringAttemptsLocationMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_HideGatheringAttemptsLocationMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_HideGatheringBoonLocationMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_HideGatheringBoonLocationMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_HideGatheringYieldLocationMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_HideGatheringYieldLocationMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_MateriaDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_MateriaDropdownHeader", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowCosmicDailyProgress {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowCosmicDailyProgress", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowCosmicRewards {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowCosmicRewards", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowDesynthesisLevelIncreasesMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowDesynthesisLevelIncreasesMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowFishAddedToGuideMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowFishAddedToGuideMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowFishSizeMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowFishSizeMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowLocationGatheringEffectMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowLocationGatheringEffectMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowMateriaExtractedMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowMateriaExtractedMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowMateriaSuccesfullyAttachedMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowMateriaSuccesfullyAttachedMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowObtainedItemsFromDesynthesisMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowObtainedItemsFromDesynthesisMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowObtainedSandsFromAetherialReductionMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowObtainedSandsFromAetherialReductionMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowOtherPlayerCompletedSynthesisMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowOtherPlayerCompletedSynthesisMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowStellarMissionMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowStellarMissionMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowSuccesfullyRetrievedMateriaMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowSuccesfullyRetrievedMateriaMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_ShowTrialSynthesisMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowTrialSynthesisMessages", resourceCulture);
            }
        }
        
        internal static string CraftingGatheringTab_StellarMissionsDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_StellarMissionsDropdownHeader", resourceCulture);
            }
        }
        
        internal static string EmotesTab_FilterCustomEmoteChannel {
            get {
                return ResourceManager.GetString("EmotesTab_FilterCustomEmoteChannel", resourceCulture);
            }
        }
        
        internal static string EmotesTab_FilterCustomEmoteChannelHelpMarker {
            get {
                return ResourceManager.GetString("EmotesTab_FilterCustomEmoteChannelHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_BlockCountHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_BlockCountHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_BlockedMessages {
            get {
                return ResourceManager.GetString("GeneralTab_BlockedMessages", resourceCulture);
            }
        }
        
        internal static string GeneralTab_CopySayMessage {
            get {
                return ResourceManager.GetString("GeneralTab_CopySayMessage", resourceCulture);
            }
        }
        
        internal static string GeneralTab_CopySayMessageHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_CopySayMessageHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_EmoteFiltersHeaderDropdown {
            get {
                return ResourceManager.GetString("GeneralTab_EmoteFiltersHeaderDropdown", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterCraftingSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterCraftingSpam", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterCraftingSpamHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterCraftingSpamHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterCustomEmotes {
            get {
                return ResourceManager.GetString("GeneralTab_FilterCustomEmotes", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterCustomEmotesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterCustomEmotesHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterEmotes {
            get {
                return ResourceManager.GetString("GeneralTab_FilterEmotes", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterEmotesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterEmotesHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterGatheringSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterGatheringSpam", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterGatheringSpamHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterGatheringSpamHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterLootSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterLootSpam", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterLootSpamHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterLootSpamHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterObtainedSpamHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterObtainedSpamHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterObtianedSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterObtianedSpam", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterProgressSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterProgressSpam", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterProgressSpamHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterProgressSpamHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterSelfEmotes {
            get {
                return ResourceManager.GetString("GeneralTab_FilterSelfEmotes", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterSelfEmotesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterSelfEmotesHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_FilterSystemSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterSystemSpam", resourceCulture);
            }
        }
        
        internal static string GeneralTab_HideKofiButton {
            get {
                return ResourceManager.GetString("GeneralTab_HideKofiButton", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedCommendationsDutyName {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedCommendationsDutyName", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedCommendationsDutyNameHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedCommendationsDutyNameHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedInstanceMessaging {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedInstanceMessaging", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedInstanceMessagingHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedInstanceMessagingHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedMessagesHeader {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedMessagesHeader", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedNoviceNetworkMessages {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedNoviceNetworkMessages", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedNoviceNetworkMessagesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedNoviceNetworkMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedPlayerCommendations {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedPlayerCommendations", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedPlayerCommendationsHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedPlayerCommendationsHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedSayMessages {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedSayMessages", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedSayMessagesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedSayMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedTreasureDungeonMessages {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedTreasureDungeonMessages", resourceCulture);
            }
        }
        
        internal static string GeneralTab_ImprovedTreasureDungeonMessagesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedTreasureDungeonMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string GeneralTab_InstanceInDTRBar {
            get {
                return ResourceManager.GetString("GeneralTab_InstanceInDTRBar", resourceCulture);
            }
        }
        
        internal static string GeneralTab_TidyChatTag {
            get {
                return ResourceManager.GetString("GeneralTab_TidyChatTag", resourceCulture);
            }
        }
        
        internal static string GeneralTab_TidyChatTagHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_TidyChatTagHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_BattleCurrenciesDropdownHeader {
            get {
                return ResourceManager.GetString("ObtainTab_BattleCurrenciesDropdownHeader", resourceCulture);
            }
        }
        
        internal static string ObtainTab_BeastTribeQuestsDropdownHeader {
            get {
                return ResourceManager.GetString("ObtainTab_BeastTribeQuestsDropdownHeader", resourceCulture);
            }
        }
        
        internal static string ObtainTab_CastYourLotHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_CastYourLotHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_CastYourLotMessages {
            get {
                return ResourceManager.GetString("ObtainTab_CastYourLotMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_CommonCurrenciesDropdownHeader {
            get {
                return ResourceManager.GetString("ObtainTab_CommonCurrenciesDropdownHeader", resourceCulture);
            }
        }
        
        internal static string ObtainTab_LootingAndRollingDropdownHeader {
            get {
                return ResourceManager.GetString("ObtainTab_LootingAndRollingDropdownHeader", resourceCulture);
            }
        }
        
        internal static string ObtainTab_OtherObtainMessagesDropdownHeader {
            get {
                return ResourceManager.GetString("ObtainTab_OtherObtainMessagesDropdownHeader", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowAlliedSealsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAlliedSealsMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowAlliedSealsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAlliedSealsMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowAnotherPlayerCastsLotMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAnotherPlayerCastsLotMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowAnotherPlayerCastsLotMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAnotherPlayerCastsLotMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowAnotherPlayerObtainsItemMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAnotherPlayerObtainsItemMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowAnotherPlayerObtainsItemMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAnotherPlayerObtainsItemMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowAnotherPlayerRollsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAnotherPlayerRollsMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowBeastTribeCraftingMaterialsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowBeastTribeCraftingMaterialsMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowBeastTribeCraftingMaterialsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowBeastTribeCraftingMaterialsMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowBeastTribeCurrenciesMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowBeastTribeCurrenciesMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowBeastTribeCurrenciesMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowBeastTribeCurrenciesMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowCenturioSealsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowCenturioSealsMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowCenturioSealsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowCenturioSealsMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowCrackedClustersMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowCrackedClustersMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowCrackedClustersMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowCrackedClustersMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowElementalShardsCrystalsClustersMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowElementalShardsCrystalsClustersMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowElementalShardsCrystalsClustersMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowElementalShardsCrystalsClustersMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowGil {
            get {
                return ResourceManager.GetString("ObtainTab_ShowGil", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowGilHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowGilHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowGrandCompanySealsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowGrandCompanySealsMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowGrandCompanySealsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowGrandCompanySealsMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowMathematicsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowMathematicsMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowMathematicsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowMathematicsMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowMGPMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowMGPMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowMGPMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowMGPMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowMnemonicsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowMnemonicsMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowMnemonicsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowMnemonicsMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowPoeticsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowPoeticsMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowPoeticsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowPoeticsMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowSacksOfNutsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowSacksOfNutsMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowSacksOfNutsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowSacksOfNutsMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowVentureMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowVentureMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowVentureMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowVentureMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowWolfMarksMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowWolfMarksMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowWolfMarksMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowWolfMarksMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowYouRolledMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowYouRolledMessages", resourceCulture);
            }
        }
        
        internal static string ObtainTab_ShowYouRolledMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowYouRolledMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowAdventurerInNeedAwardMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowAdventurerInNeedAwardMessages", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowAdventurerInNeedAwardMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowAdventurerInNeedAwardMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowBonusAwardForDutyRouletteMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowBonusAwardForDutyRouletteMessages", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowBonusAwardForDutyRouletteMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowBonusAwardForDutyRouletteMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowEarnedAchievementMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowEarnedAchievementMessages", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowExperienceGainMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowExperienceGainMessages", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowExperienceGainMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowExperienceGainMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowLevelUpMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowLevelUpMessages", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowLevelUpMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowLevelUpMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowOtherPlayerLevelUpMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowOtherPlayerLevelUpMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowOtherPlayersEarnedAchievementMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowOtherPlayersEarnedAchievementMessages", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowOtherPlayersLevelUpMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowOtherPlayersLevelUpMessages", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowPVPExpGainMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowPVPExpGainMessages", resourceCulture);
            }
        }
        
        internal static string ProgressTab_ShowPVPExpGainMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowPVPExpGainMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SettingsTabFooter_SupportOnKofiButtonText {
            get {
                return ResourceManager.GetString("SettingsTabFooter_SupportOnKofiButtonText", resourceCulture);
            }
        }
        
        internal static string SettingsTabFooter_WikiPageButtonText {
            get {
                return ResourceManager.GetString("SettingsTabFooter_WikiPageButtonText", resourceCulture);
            }
        }
        
        internal static string SystemTab_DeepDungeonsDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_DeepDungeonsDropdownHeader", resourceCulture);
            }
        }
        
        internal static string SystemTab_ErrorMessagesDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_ErrorMessagesDropdownHeader", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowAetherCompassMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAetherCompassMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowAetherCompassMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowAetherCompassMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowAirshipVoyageMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAirshipVoyageMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowAirshipVoyageMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowAirshipVoyageMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowCompletedVenture {
            get {
                return ResourceManager.GetString("SystemTab_ShowCompletedVenture", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowCompletedVentureHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowCompletedVentureHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowFateLevelSyncMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowFateLevelSyncMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowFateLevelSyncMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowFateLevelSyncMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowItemSearchResultsMessage {
            get {
                return ResourceManager.GetString("SystemTab_ShowItemSearchResultsMessage", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowItemSearchResultsMessageHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowItemSearchResultsMessageHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowReceivedCommendations {
            get {
                return ResourceManager.GetString("SystemTab_ShowReceivedCommendations", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowReceivedCommendationsHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowReceivedCommendationsHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowSayReminder {
            get {
                return ResourceManager.GetString("SystemTab_ShowSayReminder", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowSayReminderHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowSayReminderHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowShownDefaultDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_ShowShownDefaultDropdownHeader", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowSRankSpawnAnnouncement {
            get {
                return ResourceManager.GetString("SystemTab_ShowSRankSpawnAnnouncement", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowSRankSpawnAnnouncementHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowSRankSpawnAnnouncementHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowSSRankMinionSpawnAnnouncement {
            get {
                return ResourceManager.GetString("SystemTab_ShowSSRankMinionSpawnAnnouncement", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowSSRankMinionSpawnAnnouncementHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowSSRankMinionSpawnAnnouncementHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowSubmarineVoyageMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowSubmarineVoyageMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowSubmarineVoyageMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowSubmarineVoyageMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowTryOnGlamourMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowTryOnGlamourMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowTryOnGlamourMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowTryOnGlamourMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowVistaMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowVistaMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowVistaMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowVistaMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowYouSenseSomethingMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowYouSenseSomethingMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowYouSenseSomethingMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowYouSenseSomethingMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_PartyAndInviteDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_PartyAndInviteDropdownHeader", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowAccursedHoardDiscoveredMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAccursedHoardDiscoveredMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowAccursedHoardNotSensedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAccursedHoardNotSensedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowAccursedHoardSensedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAccursedHoardSensedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowAetherpoolIncreasesMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAetherpoolIncreasesMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowAetherpoolRemainsUnchangedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAetherpoolRemainsUnchangedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowCairnOfPassageActivatedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowCairnOfPassageActivatedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowCairnOfPassageGlowsMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowCairnOfPassageGlowsMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowCairnOfReturnUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowCairnOfReturnUsedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowCompletionTimeForUnrestrictedParty {
            get {
                return ResourceManager.GetString("SystemTab_ShowCompletionTimeForUnrestrictedParty", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowCompletionTimeForUnrestrictedPartyHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowCompletionTimeForUnrestrictedPartyHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowDisbandAndDissolveMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowDisbandAndDissolveMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowFloorNumberMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowFloorNumberMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowGearsetChangingMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowGearsetChangingMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowGearsetChangingMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowGearsetChangingMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowHiddenMessagesDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_ShowHiddenMessagesDropdownHeader", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowHuntMarkSlainMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowHuntMarkSlainMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowHuntMarkSlainMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowHuntMarkSlainMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowJoinedCrossworldPartyMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowJoinedCrossworldPartyMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowJoiningPartyMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowJoiningPartyMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowLeftPartyMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowLeftPartyMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowMailAttachmentMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowMailAttachmentMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowMailAttachmentMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowMailAttachmentMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowObtainedPomanderMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowObtainedPomanderMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowOnlineStatusMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowOnlineStatusMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowOnlineStatusMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowOnlineStatusMessagesHelpMarker", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowPomanderOfAffluenceUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfAffluenceUsedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowPomanderOfAlterationUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfAlterationUsedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowPomanderOfFlightUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfFlightUsedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowPomanderOfSafetyUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfSafetyUsedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowPomanderOfSerenityUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfSerenityUsedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowPomanderOfSightUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfSightUsedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowPomanderOfWitchingUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfWitchingUsedMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowSentPartyInviteMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowSentPartyInviteMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowTeleportOfferFromPartyMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowTeleportOfferFromPartyMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_ShowTransferenceMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowTransferenceMessages", resourceCulture);
            }
        }
        
        internal static string SystemTab_TradingDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_TradingDropdownHeader", resourceCulture);
            }
        }
        
        internal static string WhitelistTab_ExactNameMatchWhitelistExplanation {
            get {
                return ResourceManager.GetString("WhitelistTab_ExactNameMatchWhitelistExplanation", resourceCulture);
            }
        }
        
        internal static string WhitelistTab_ExplanationMessage {
            get {
                return ResourceManager.GetString("WhitelistTab_ExplanationMessage", resourceCulture);
            }
        }
        
        internal static string WhitelistTab_PlayerInformationTableHeader {
            get {
                return ResourceManager.GetString("WhitelistTab_PlayerInformationTableHeader", resourceCulture);
            }
        }
        
        internal static string WhitelistTab_SelectChannelsHeader {
            get {
                return ResourceManager.GetString("WhitelistTab_SelectChannelsHeader", resourceCulture);
            }
        }
        
        internal static string WhitelistTab_ShowAllMessagesByWhitelistedPlayer {
            get {
                return ResourceManager.GetString("WhitelistTab_ShowAllMessagesByWhitelistedPlayer", resourceCulture);
            }
        }
        
        internal static string WhitelistTab_ShowAllMessagesTargetingWhitelistedPlayer {
            get {
                return ResourceManager.GetString("WhitelistTab_ShowAllMessagesTargetingWhitelistedPlayer", resourceCulture);
            }
        }
        
        internal static string WhitelistTab_WhitelistedPlayerFirstName {
            get {
                return ResourceManager.GetString("WhitelistTab_WhitelistedPlayerFirstName", resourceCulture);
            }
        }
        
        internal static string WhitelistTab_WhitelistedPlayerLastName {
            get {
                return ResourceManager.GetString("WhitelistTab_WhitelistedPlayerLastName", resourceCulture);
            }
        }
        
        internal static string WhitelistTab_WhitelistedPlayerServerName {
            get {
                return ResourceManager.GetString("WhitelistTab_WhitelistedPlayerServerName", resourceCulture);
            }
        }
    }
}
