//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TidyChat.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages_ploc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages_ploc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TidyChat.Localization.Resources.Languages.ploc", typeof(Languages_ploc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çĥàţ Ĥîšţôŕý.
        /// </summary>
        internal static string AdvancedTab_ChatHistoryTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_ChatHistoryTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çŕàƒţîñĝ/Ĝàţĥéŕîñĝ.
        /// </summary>
        internal static string AdvancedTab_CraftingGatheringTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_CraftingGatheringTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éñàƀļé ðéƀûĝ ɱôðé.
        /// </summary>
        internal static string AdvancedTab_EnableDebugMode {
            get {
                return ResourceManager.GetString("AdvancedTab_EnableDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ļôôţ/Ôƀţàîñ.
        /// </summary>
        internal static string AdvancedTab_LootObtainTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_LootObtainTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Þŕôĝŕéšš.
        /// </summary>
        internal static string AdvancedTab_ProgressTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_ProgressTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šýšţéɱ.
        /// </summary>
        internal static string AdvancedTab_SystemTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_SystemTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ŵĥîţéļîšţ.
        /// </summary>
        internal static string AdvancedTab_WhitelistTabHeader {
            get {
                return ResourceManager.GetString("AdvancedTab_WhitelistTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ƒŕôɱ çôɱþļéţîñĝ.
        /// </summary>
        internal static string BetterStrings_CommendationsFromCompletingDuty {
            get {
                return ResourceManager.GetString("BetterStrings_CommendationsFromCompletingDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to çôɱɱéñðàţîôñ.
        /// </summary>
        internal static string BetterStrings_CommendationSingular {
            get {
                return ResourceManager.GetString("BetterStrings_CommendationSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to çôɱɱéñðàţîôñš.
        /// </summary>
        internal static string BetterStrings_CommendationsPlural {
            get {
                return ResourceManager.GetString("BetterStrings_CommendationsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ýôû ŕéçéîṽéð {0} {1}{2}.
        /// </summary>
        internal static string BetterStrings_ReceivedCommendationsMessages {
            get {
                return ResourceManager.GetString("BetterStrings_ReceivedCommendationsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ñûɱƀéŕ ôƒ šéçôñðš ţô ķééþ ɱéššàĝéš îñ çĥàţ ĥîšţôŕý.
        /// </summary>
        internal static string ChatHistoryTab_ChatHistoryTimer {
            get {
                return ResourceManager.GetString("ChatHistoryTab_ChatHistoryTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šéţ ţô ⓞ ţô ðîšàƀļé.
        /// </summary>
        internal static string ChatHistoryTab_ChatHistoryTimerHelpMarker {
            get {
                return ResourceManager.GetString("ChatHistoryTab_ChatHistoryTimerHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çŕàƒţîñĝ.
        /// </summary>
        internal static string ChatHistoryTab_CraftingChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_CraftingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éɱôţéš.
        /// </summary>
        internal static string ChatHistoryTab_EmotesChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_EmotesChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éñàƀļé Çĥàţ Ĥîšţôŕý Ƒîļţéŕ.
        /// </summary>
        internal static string ChatHistoryTab_EnableChatHistoryFilter {
            get {
                return ResourceManager.GetString("ChatHistoryTab_EnableChatHistoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îƒ à ɱéššàĝé ŵàš šéñţ ŵîţĥîñ ţĥé ļàšţ {0} ɱéššàĝéš îţ ŵîļļ ƀé ƒîļţéŕéð.
        /// </summary>
        internal static string ChatHistoryTab_EnableChatHistoryFilterHelpMarker {
            get {
                return ResourceManager.GetString("ChatHistoryTab_EnableChatHistoryFilterHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĝàţĥéŕîñĝ.
        /// </summary>
        internal static string ChatHistoryTab_GatheringChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_GatheringChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îĝñôŕé ɱéššàĝéš šéñţ ƀý þļàýéŕ.
        /// </summary>
        internal static string ChatHistoryTab_IgnoreMessagesSentByPlayer {
            get {
                return ResourceManager.GetString("ChatHistoryTab_IgnoreMessagesSentByPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîļţéŕš ðûþļîçàţé ɱéššàĝéš šéñţ ƀý ţĥé þļàýéŕ، éñàƀļé îƒ ýôû ŵàñţ ðûþļîçàţé ɱéššàĝéš ýôû šéñţ ţô ƀé ƒîļţéŕéð ƒŕôɱ ýôûŕ ṽîéŵ·.
        /// </summary>
        internal static string ChatHistoryTab_IgnoreMessagesSentByPlayerHelpMarker {
            get {
                return ResourceManager.GetString("ChatHistoryTab_IgnoreMessagesSentByPlayerHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ñûɱƀéŕ ôƒ ɱéššàĝéš ţô ķééþ îñ çĥàţ ĥîšţôŕý.
        /// </summary>
        internal static string ChatHistoryTab_LengthOfChatHistory {
            get {
                return ResourceManager.GetString("ChatHistoryTab_LengthOfChatHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŴÀŔÑÎÑĜ∶ Ĥàṽîñĝ ţĥé ĥîšţôŕý ļéñĝţĥ šéţ ţôô ĥîĝĥ ɱàý îɱþàçţ ĝàɱé þéŕƒôŕɱàñçé·
        ///Îţ&apos;š ŕéçôɱɱéñðéð ţô ķééþ îţ àţ ⑤ⓞ ôŕ ļôŵéŕ·.
        /// </summary>
        internal static string ChatHistoryTab_LengthOfChatHistoryWarningMessage {
            get {
                return ResourceManager.GetString("ChatHistoryTab_LengthOfChatHistoryWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ļôĝîñ/Ļôĝôûţ.
        /// </summary>
        internal static string ChatHistoryTab_LoginLogoutChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_LoginLogoutChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ļôôţ.
        /// </summary>
        internal static string ChatHistoryTab_LootChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_LootChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Þŕôĝŕéšš.
        /// </summary>
        internal static string ChatHistoryTab_ProgressChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_ProgressChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šéļéçţ çĥàññéļš ƒôŕ Çĥàţ Ĥîšţôŕý ţô ƒîļţéŕ∶.
        /// </summary>
        internal static string ChatHistoryTab_SelectChannels {
            get {
                return ResourceManager.GetString("ChatHistoryTab_SelectChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šýšţéɱ.
        /// </summary>
        internal static string ChatHistoryTab_SystemChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_SystemChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţàļķîñĝ.
        /// </summary>
        internal static string ChatHistoryTab_TalkingChannel {
            get {
                return ResourceManager.GetString("ChatHistoryTab_TalkingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Àðṽàñçéð.
        /// </summary>
        internal static string ConfigWindow_AdvancedSettingsTabHeader {
            get {
                return ResourceManager.GetString("ConfigWindow_AdvancedSettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šéţţîñĝš.
        /// </summary>
        internal static string ConfigWindow_SettingsTabHeader {
            get {
                return ResourceManager.GetString("ConfigWindow_SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çŕàƒţîñĝ.
        /// </summary>
        internal static string CraftingGatheringTab_CraftingDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_CraftingDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ðéšýñţĥéšîš.
        /// </summary>
        internal static string CraftingGatheringTab_DesynthesisDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_DesynthesisDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîšĥîñĝ.
        /// </summary>
        internal static string CraftingGatheringTab_FishingDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_FishingDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĝàţĥéŕîñĝ Ļôçàţîôñš.
        /// </summary>
        internal static string CraftingGatheringTab_GatheringLocationsDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_GatheringLocationsDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé ôñļý ļôçàţîôñš ţĥàţ àƒƒéçţ ĝàţĥéŕîñĝ àţţéɱþţš.
        /// </summary>
        internal static string CraftingGatheringTab_HideGatheringAttemptsLocationMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_HideGatheringAttemptsLocationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé ôñļý ļôçàţîôñš ţĥàţ àƒƒéçţ Ĝàţĥéŕéŕ&apos;š Ɓôôñ.
        /// </summary>
        internal static string CraftingGatheringTab_HideGatheringBoonLocationMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_HideGatheringBoonLocationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé ôñļý ļôçàţîôñš ţĥàţ àƒƒéçţ ĝàţĥéŕîñĝ ýîéļð.
        /// </summary>
        internal static string CraftingGatheringTab_HideGatheringYieldLocationMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_HideGatheringYieldLocationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ṁàţéŕîà.
        /// </summary>
        internal static string CraftingGatheringTab_MateriaDropdownHeader {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_MateriaDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ðéšýñţĥéšîš ļéṽéļ îñçŕéàšéš ɱéššàĝéš.
        /// </summary>
        internal static string CraftingGatheringTab_ShowDesynthesisLevelIncreasesMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowDesynthesisLevelIncreasesMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ɱéššàĝé ŵĥéñ à ƒîšĥ îš àððéð ţô ţĥé ƒîšĥ ĝûîðé.
        /// </summary>
        internal static string CraftingGatheringTab_ShowFishAddedToGuideMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowFishAddedToGuideMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ çàûĝĥţ ƒîšĥ ɱéàšûŕîñĝ [size] îļɱš.
        /// </summary>
        internal static string CraftingGatheringTab_ShowFishSizeMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowFishSizeMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ɱéššàĝé ŵĥéñ ļôçàţîôñ àƒƒéçţš ĝàţĥéŕîñĝ ýîéļð، ŕéçéîṽîñĝ Ĝàţĥéŕéŕ&apos;š Ɓôôñ، ôŕ ĝàţĥéŕîñĝ àţţéɱþţš.
        /// </summary>
        internal static string CraftingGatheringTab_ShowLocationGatheringEffectMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowLocationGatheringEffectMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ɱéššàĝé ŵĥéñ ɱàţéŕîà îš éẋţŕàçţéð ƒŕôɱ šþîŕîţƀôñðéð ĝéàŕ.
        /// </summary>
        internal static string CraftingGatheringTab_ShowMateriaExtractedMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowMateriaExtractedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ɱéššàĝé ŵĥéñ ɱàţéŕîà ƒàîļš ţô ƀé ôṽéŕɱéļðéð ôñţô ĝéàŕ.
        /// </summary>
        internal static string CraftingGatheringTab_ShowMateriaOvermeldFailuresMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowMateriaOvermeldFailuresMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ɱéššàĝé ŵĥéñ ɱàţéŕîà šĥàţţéŕš ðûŕîñĝ ŕéţŕîéṽàļ.
        /// </summary>
        internal static string CraftingGatheringTab_ShowMateriaShattersMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowMateriaShattersMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ɱéššàĝé ŵĥéñ ɱàţéŕîà îš šûççéšƒûļļý àţţàçĥéð ţô ĝéàŕ.
        /// </summary>
        internal static string CraftingGatheringTab_ShowMateriaSuccesfullyAttachedMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowMateriaSuccesfullyAttachedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ôƀţàîñéð îţéɱš ƒŕôɱ ðéšýñţĥéšîš.
        /// </summary>
        internal static string CraftingGatheringTab_ShowObtainedItemsFromDesynthesisMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowObtainedItemsFromDesynthesisMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ţĥé ñûɱƀéŕ ôƒ ôƀţàîñéð šàñðš àƒţéŕ ûšîñĝ àéţĥéŕîàļ ŕéðûçţîôñ.
        /// </summary>
        internal static string CraftingGatheringTab_ShowObtainedSandsFromAetherialReductionMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowObtainedSandsFromAetherialReductionMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ šýñţĥéšîš ɱéššàĝé ŵĥéñ ôţĥéŕ þļàýéŕš çôɱþļéţé à çŕàƒţ·.
        /// </summary>
        internal static string CraftingGatheringTab_ShowOtherPlayerCompletedSynthesisMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowOtherPlayerCompletedSynthesisMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ɱéššàĝé ŵĥéñ ýôû šûççéšƒûļļý ŕéţŕîéṽé ɱàţéŕîà ƒŕôɱ ĝéàŕ.
        /// </summary>
        internal static string CraftingGatheringTab_ShowSuccesfullyRetrievedMateriaMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowSuccesfullyRetrievedMateriaMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ƒîñàļ šţàţûš ɱéššàĝéš ûþôñ ƒîñîšĥîñĝ à Ţŕîàļ šýñţĥéšîš.
        /// </summary>
        internal static string CraftingGatheringTab_ShowTrialSynthesisMessages {
            get {
                return ResourceManager.GetString("CraftingGatheringTab_ShowTrialSynthesisMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çôûñţ îš ôñļý ûþðàţéð éṽéŕý ①ⓞⓞ ƀļôçķéð ɱéššàĝéš، ŵĥéñ çĥàñĝîñĝ žôñéš، ôŕ ŵĥéñ ļôĝĝîñĝ ôƒƒ·.
        /// </summary>
        internal static string GeneralTab_BlockCountHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_BlockCountHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţîðý Çĥàţ ĥàš ƀļôçķéð {0:n0} ɱéššàĝéš šô ƒàŕ·.
        /// </summary>
        internal static string GeneralTab_BlockedMessages {
            get {
                return ResourceManager.GetString("GeneralTab_BlockedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Àûţôɱàţîçàļļý çôþý îɱþŕôṽéð /šàý ɱéššàĝé ţô çļîþƀôàŕð.
        /// </summary>
        internal static string GeneralTab_CopySayMessage {
            get {
                return ResourceManager.GetString("GeneralTab_CopySayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ŕéǫûîŕéš Îɱþŕôṽéð /Šàý ɱéššàĝé ƒôŕ ǫûéšţš ţô ƀé éñàƀļéð.
        /// </summary>
        internal static string GeneralTab_CopySayMessageHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_CopySayMessageHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éɱôţé Ƒîļţéŕš.
        /// </summary>
        internal static string GeneralTab_EmoteFiltersHeaderDropdown {
            get {
                return ResourceManager.GetString("GeneralTab_EmoteFiltersHeaderDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîļţéŕ Çŕàƒţîñĝ šþàɱ.
        /// </summary>
        internal static string GeneralTab_FilterCraftingSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterCraftingSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ƒîļţéŕ îñçļûðéš àļļ çŕàƒţîñĝ ɱéššàĝéš éẋçéþţ &quot;Ýôû šýñţĥéšîžé à/àñ &lt;item&gt;&quot;
        ///Ţĥîš àļļôŵš ýôû ţô ûšé ÇĥàţÀļéŕţš ţô çŕéàţé àñ àļéŕţ ƒôŕ &quot;Ýôû šýñţĥéšîžé&quot; îñšţéàð ôƒ ûšîñĝ ɱàçŕô‐ƒîñîšĥéð àļéŕţš.
        /// </summary>
        internal static string GeneralTab_FilterCraftingSpamHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterCraftingSpamHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîļţéŕ çûšţôɱ éɱôţé šþàɱ.
        /// </summary>
        internal static string GeneralTab_FilterCustomEmotes {
            get {
                return ResourceManager.GetString("GeneralTab_FilterCustomEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ ĥîðé àļļ &quot;/éɱ&quot; ɱéššàĝéš ûñļéšš îţ ɱéñţîôñš ýôû ôŕ îš à çûšţôɱ éɱôţé ýôû ûšéð·
        ///éĝ· Àñôţĥéŕ Þļàýéŕ ļéàñš ôṽéŕ àñð ĝîṽéš ýôû à ƀîĝ ƀéàŕ ĥûĝ·.
        /// </summary>
        internal static string GeneralTab_FilterCustomEmotesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterCustomEmotesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîļţéŕ éɱôţé šþàɱ.
        /// </summary>
        internal static string GeneralTab_FilterEmotes {
            get {
                return ResourceManager.GetString("GeneralTab_FilterEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ ĥîðé àļļ éɱôţé ţéẋţ ûñļéšš îţ îš àñ éɱôţé ţàŕĝéţîñĝ ýôû ôŕ àñ éɱôţé ýôû ûšéð·.
        /// </summary>
        internal static string GeneralTab_FilterEmotesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterEmotesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîļţéŕ Ĝàţĥéŕîñĝ šþàɱ.
        /// </summary>
        internal static string GeneralTab_FilterGatheringSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterGatheringSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ƒîļţéŕ îñçļûðéš &quot;ýôû ƀéĝîñ/ƒîñîšĥ&quot; ĝàţĥéŕîñĝ ɱéššàĝéš، àš ŵéļļ àš ļôçàţîôñ àƒƒéçţš.
        /// </summary>
        internal static string GeneralTab_FilterGatheringSpamHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterGatheringSpamHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîļţéŕ Ļôôţ ŕôļļ šþàɱ.
        /// </summary>
        internal static string GeneralTab_FilterLootSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterLootSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ƒîļţéŕ îñçļûðéš ɱéššàĝéš ļîķé ŕôļļîñĝ ĝŕééð ôŕ þļàýéŕ ôƀţàîñéð à ĝéàŕ þîéçé.
        /// </summary>
        internal static string GeneralTab_FilterLootSpamHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterLootSpamHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ƒîļţéŕ îñçļûðéš îţéɱš ôƀţàîñéð àš ɱôñšţéŕ ðŕôþš، ǫûéšţ ŕéŵàŕðš، àñð ŕôûļéţţé ŕéŵàŕðš.
        /// </summary>
        internal static string GeneralTab_FilterObtainedSpamHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterObtainedSpamHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîļţéŕ Ôƀţàîñéð îţéɱ šþàɱ.
        /// </summary>
        internal static string GeneralTab_FilterObtianedSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterObtianedSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîļţéŕ Þŕôĝŕéšš šþàɱ.
        /// </summary>
        internal static string GeneralTab_FilterProgressSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterProgressSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥéšé ƒîļţéŕš îñçļûðé ɱéššàĝéš ļîķé éàŕñéð àçĥîéṽéɱéñţš ôŕ éẋþéŕîéñçé þôîñţš.
        /// </summary>
        internal static string GeneralTab_FilterProgressSpamHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterProgressSpamHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîļţéŕ éɱôţéš ûšéð ƀý ýôûŕšéļƒ.
        /// </summary>
        internal static string GeneralTab_FilterSelfEmotes {
            get {
                return ResourceManager.GetString("GeneralTab_FilterSelfEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ ĥîðé ţĥé ɱéššàĝé ţĥàţ ôççûŕš ŵĥéñ ýôû ûšé àñ éɱôţé ôŕ çûšţôɱ éɱôţé·
        ///éĝ· Ýôû ĝéñţļý þàţ &lt;user&gt;.
        /// </summary>
        internal static string GeneralTab_FilterSelfEmotesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_FilterSelfEmotesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîļţéŕ Šýšţéɱ šþàɱ.
        /// </summary>
        internal static string GeneralTab_FilterSystemSpam {
            get {
                return ResourceManager.GetString("GeneralTab_FilterSystemSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé ķô‐ƒî ƀûţţôñ.
        /// </summary>
        internal static string GeneralTab_HideKofiButton {
            get {
                return ResourceManager.GetString("GeneralTab_HideKofiButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îñçļûðé ðûţý ñàɱé ŵîţĥ çôɱɱéñðàţîôñ ɱéššàĝéš.
        /// </summary>
        internal static string GeneralTab_ImprovedCommendationsDutyName {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedCommendationsDutyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ŕéǫûîŕéš Îɱþŕôṽéð Þļàýéŕ Çôɱɱéñðàţîôñš ţô ƀé éñàƀļéð.
        /// </summary>
        internal static string GeneralTab_ImprovedCommendationsDutyNameHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedCommendationsDutyNameHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îɱþŕôṽéð /îñšţàñçé ɱéššàĝîñĝ.
        /// </summary>
        internal static string GeneralTab_ImprovedInstanceMessaging {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedInstanceMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çĥàñĝéš ţĥé îñšţàñçé ţéẋţ ţô∶ Ýôû àŕé ñôŵ îñ îñšţàñçé∶ #.
        /// </summary>
        internal static string GeneralTab_ImprovedInstanceMessagingHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedInstanceMessagingHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îɱþŕôṽéð Ṁéššàĝéš.
        /// </summary>
        internal static string GeneralTab_ImprovedMessagesHeader {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedMessagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îɱþŕôṽéð Ñôṽîçé Ñéţŵôŕķ ĵôîñ àñð ļéàṽé ɱéššàĝéš.
        /// </summary>
        internal static string GeneralTab_ImprovedNoviceNetworkMessages {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedNoviceNetworkMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ŕéðûçéš ţĥé àɱôûñţ ôƒ Ñôṽîçé Ñéţŵôŕķ ţéẋţ ŵĥéñ ţĥé Ñôṽîçé Ñéţŵôŕķ îš ĵôîñéð àñð çĥàñĝéš ţĥé ļéàṽé ɱéššàĝé ţô ƀé çôñšîšţéñţļý ŵôŕðéð·.
        /// </summary>
        internal static string GeneralTab_ImprovedNoviceNetworkMessagesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedNoviceNetworkMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îɱþŕôṽéð Þļàýéŕ Çôɱɱéñðàţîôñš.
        /// </summary>
        internal static string GeneralTab_ImprovedPlayerCommendations {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedPlayerCommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ðîšàƀļéš Šýšţéɱ ɱéššàĝé ƒôŕ ŕéçéîṽéð çôɱɱéñðàţîôñš àñð îñšţéàð ļôĝš à šîñĝļé ɱéššàĝé ţô ýôûŕ Ðàļàɱûð Ĝéñéŕàļ Çĥàţ Çĥàññéļ (çĥéçķ ýôûŕ Ðàļàɱûð Ĝéñéŕàļ Šéţţîñĝš ƒôŕ ŵĥîçĥ çĥàññéļ ţĥàţ îš ‐ îţ îš Ðéƀûĝ ƀý ðéƒàûļţ).
        /// </summary>
        internal static string GeneralTab_ImprovedPlayerCommendationsHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedPlayerCommendationsHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îɱþŕôṽéð /Šàý ɱéššàĝéš ƒôŕ ǫûéšţš.
        /// </summary>
        internal static string GeneralTab_ImprovedSayMessages {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedSayMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ŵĥéñ à ǫûéšţ ŕéǫûîŕéš ýôû ţô /Šàý šôɱéţĥîñĝ îñ çĥàţ، çĥàñĝé ţĥé ɱéššàĝé îñţô ôñé ţĥàţ çàñ ƀé çôþý àñð þàšţéð éàšîļý.
        /// </summary>
        internal static string GeneralTab_ImprovedSayMessagesHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_ImprovedSayMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ðîšþļàý çûŕŕéñţ îñšţàñçé îñ ÐŢŔ Ɓàŕ.
        /// </summary>
        internal static string GeneralTab_InstanceInDTRBar {
            get {
                return ResourceManager.GetString("GeneralTab_InstanceInDTRBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Àðð [TidyChat] ţàĝ ţô àñý ɱôðîƒîéð ɱéššàĝéš.
        /// </summary>
        internal static string GeneralTab_TidyChatTag {
            get {
                return ResourceManager.GetString("GeneralTab_TidyChatTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Þŕéþéñðš ɱéššàĝéš šéñţ ôŕ ɱôðîƒîéð ƀý Ţîðý Çĥàţ ŵîţĥ [TidyChat].
        /// </summary>
        internal static string GeneralTab_TidyChatTagHelpMarker {
            get {
                return ResourceManager.GetString("GeneralTab_TidyChatTagHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ɓàţţļé Çûŕŕéñçîéš.
        /// </summary>
        internal static string ObtainTab_BattleCurrenciesDropdownHeader {
            get {
                return ResourceManager.GetString("ObtainTab_BattleCurrenciesDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ɓéàšţ Ţŕîƀé Ǫûéšţš.
        /// </summary>
        internal static string ObtainTab_BeastTribeQuestsDropdownHeader {
            get {
                return ResourceManager.GetString("ObtainTab_BeastTribeQuestsDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ ţĥé ɱéššàĝé ţĥàţ ôççûŕš ŵĥéñ ýôû ŕôļļ ôñ ļôôţ·
        ///éĝ· Ýôû çàšţ ýôûŕ ļôţ ƒôŕ ţĥé &lt;item&gt;.
        /// </summary>
        internal static string ObtainTab_CastYourLotHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_CastYourLotHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ &quot;Ýôû çàšţ ýôûŕ ļôţ&quot; ɱéššàĝéš.
        /// </summary>
        internal static string ObtainTab_CastYourLotMessages {
            get {
                return ResourceManager.GetString("ObtainTab_CastYourLotMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çôɱɱôñ Çûŕŕéñçîéš.
        /// </summary>
        internal static string ObtainTab_CommonCurrenciesDropdownHeader {
            get {
                return ResourceManager.GetString("ObtainTab_CommonCurrenciesDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ļôôţîñĝ ⅋ Ŕôļļîñĝ.
        /// </summary>
        internal static string ObtainTab_LootingAndRollingDropdownHeader {
            get {
                return ResourceManager.GetString("ObtainTab_LootingAndRollingDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ôţĥéŕ Ôƀţàîñ Ṁéššàĝéš.
        /// </summary>
        internal static string ObtainTab_OtherObtainMessagesDropdownHeader {
            get {
                return ResourceManager.GetString("ObtainTab_OtherObtainMessagesDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Àļļîéð Šéàļš.
        /// </summary>
        internal static string ObtainTab_ShowAlliedSealsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAlliedSealsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ ①ⓞⓞ Àļļîéð Šéàļš·.
        /// </summary>
        internal static string ObtainTab_ShowAlliedSealsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAlliedSealsMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ &quot;Àñôţĥéŕ Þļàýéŕ çàšţš ţĥéîŕ ļôţ &lt;item&gt;&quot; ɱéššàĝéš.
        /// </summary>
        internal static string ObtainTab_ShowAnotherPlayerCastsLotMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAnotherPlayerCastsLotMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ ţĥé ɱéššàĝé ţĥàţ ôççûŕš ŵĥéñ àñôţĥéŕ þļàýéŕ îñ ţĥé þàŕţý ŕôļļš ƒôŕ à ļôôţ ðŕôþ·
        ///éĝ· Šôɱé þļàýéŕ çàšţš ĥéŕ ļôţ ƒôŕ &lt;item&gt;·.
        /// </summary>
        internal static string ObtainTab_ShowAnotherPlayerCastsLotMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAnotherPlayerCastsLotMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ &quot;Àñôţĥéŕ Þļàýéŕ ôƀţàîñš &lt;item&gt;&quot; ɱéššàĝéš.
        /// </summary>
        internal static string ObtainTab_ShowAnotherPlayerObtainsItemMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAnotherPlayerObtainsItemMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ ţĥé ɱéššàĝé ţĥàţ ôççûŕš ŵĥéñ àñôţĥéŕ þļàýéŕ îñ ţĥé þàŕţý ôƀţàîñš à ļôôţ ðŕôþ·
        ///éĝ· Šôɱé þļàýéŕ ôƀţàîñš àñ &lt;item&gt;¡.
        /// </summary>
        internal static string ObtainTab_ShowAnotherPlayerObtainsItemMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAnotherPlayerObtainsItemMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ &quot;Àñôţĥéŕ Þļàýéŕ ŕôļļš Ĝŕééð···&quot; ɱéššàĝéš.
        /// </summary>
        internal static string ObtainTab_ShowAnotherPlayerRollsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAnotherPlayerRollsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Àļļàĝàñ ţôɱéšţôñéš ôƒ Àþĥôŕîšɱ.
        /// </summary>
        internal static string ObtainTab_ShowAphorismMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAphorismMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ ⑥ⓞ Àļļàĝàñ ţôɱéšţôñéš ôƒ Àþĥôŕîšɱ·.
        /// </summary>
        internal static string ObtainTab_ShowAphorismMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAphorismMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Àļļàĝàñ ţôɱéšţôñéš ôƒ Àšţŕôñôɱý.
        /// </summary>
        internal static string ObtainTab_ShowAstronomyMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAstronomyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ ②ⓞ Àļļàĝàñ ţôɱéšţôñéš ôƒ Àšţŕôñôɱý·.
        /// </summary>
        internal static string ObtainTab_ShowAstronomyMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowAstronomyMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Ɓéàšţ Ţŕîƀé çŕàƒţîñĝ ɱàţéŕîàļš.
        /// </summary>
        internal static string ObtainTab_ShowBeastTribeCraftingMaterialsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowBeastTribeCraftingMaterialsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ ţĥé ɱéššàĝé ţĥàţ ôççûŕš ŵĥéñ ýôû ŕéçéîṽé çŕàƒţîñĝ ɱàţéŕîàļš ţô ƀé ûšéð îñ Ɓéàšţ Ţŕîƀé çŕàƒţîñĝ ǫûéšţš·
        ///éĝ· Ýôû ôƀţàîñ Šţàŕƀôàŕð Ĥûļļ Çôɱþôñéñţ Ṁàţéŕîàļš.
        /// </summary>
        internal static string ObtainTab_ShowBeastTribeCraftingMaterialsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowBeastTribeCraftingMaterialsMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Ɓéàšţ Ţŕîƀé Çûŕŕéñçîéš.
        /// </summary>
        internal static string ObtainTab_ShowBeastTribeCurrenciesMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowBeastTribeCurrenciesMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ ţĥé ɱéššàĝé ţĥàţ ôççûŕš ŵĥéñ ýôû ŕéçéîṽé Ɓéàšţ Ţŕîƀé çûŕŕéñçîéš ûþôñ çôɱþļéţîôñ ôƒ à Ɓéàšţ Ţŕîƀé ǫûéšţ·.
        /// </summary>
        internal static string ObtainTab_ShowBeastTribeCurrenciesMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowBeastTribeCurrenciesMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Çéñţûŕîô Šéàļš.
        /// </summary>
        internal static string ObtainTab_ShowCenturioSealsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowCenturioSealsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ ④ⓞ Çéñţûŕîô Šéàļš·.
        /// </summary>
        internal static string ObtainTab_ShowCenturioSealsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowCenturioSealsMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ çŕàçķéð çļûšţéŕš.
        /// </summary>
        internal static string ObtainTab_ShowCrackedClustersMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowCrackedClustersMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ çŕàçķéð çļûšţéŕš šûçĥ àš Ðéñðŕôçļûšţéŕš àñð Àñţĥôçļûšţéŕš·
        ///Ƒôŕ ĥîðîñĝ éļéɱéñţàļ çļûšţéŕš šéé ţĥé ĥîðé éļéɱéñţàļ çļûšţéŕš ôþţîôñ ðôŵñ ƀéļôŵ·
        ///éĝ· Ýôû ôƀţàîñ à çŕàçķéð ðéñðŕôçļûšţéŕ.
        /// </summary>
        internal static string ObtainTab_ShowCrackedClustersMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowCrackedClustersMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ éļéɱéñţàļ šĥàŕðš، çŕýšţàļš، àñð çļûšţéŕš.
        /// </summary>
        internal static string ObtainTab_ShowElementalShardsCrystalsClustersMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowElementalShardsCrystalsClustersMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ ţĥé ɱéššàĝé ţĥàţ ôççûŕš ŵĥéñ ýôû ĝàţĥéŕ ôŕ ŕéçéîṽé éļéɱéñţàļ šĥàŕðš، çŕýšţàļš، ôŕ çļûšţéŕš
        ///éĝ· Ýôû ôƀţàîñ ③ⓞ îçé šĥàŕðš.
        /// </summary>
        internal static string ObtainTab_ShowElementalShardsCrystalsClustersMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowElementalShardsCrystalsClustersMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Ĝîļ.
        /// </summary>
        internal static string ObtainTab_ShowGil {
            get {
                return ResourceManager.GetString("ObtainTab_ShowGil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ ⑥⑨ ĝîļ·.
        /// </summary>
        internal static string ObtainTab_ShowGilHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowGilHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Ĝŕàñð Çôɱþàñý Šéàļš.
        /// </summary>
        internal static string ObtainTab_ShowGrandCompanySealsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowGrandCompanySealsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ ④②ⓞ Ƒļàɱé Šéàļš·.
        /// </summary>
        internal static string ObtainTab_ShowGrandCompanySealsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowGrandCompanySealsMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ṀĜÞ.
        /// </summary>
        internal static string ObtainTab_ShowMGPMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowMGPMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ ①①⑦ ṀĜÞ·.
        /// </summary>
        internal static string ObtainTab_ShowMGPMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowMGPMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Àļļàĝàñ ţôɱéšţôñéš ôƒ Þôéţîçš.
        /// </summary>
        internal static string ObtainTab_ShowPoeticsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowPoeticsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ ①ⓞⓞ Àļļàĝàñ ţôɱéšţôñéš ôƒ Þôéţîçš·.
        /// </summary>
        internal static string ObtainTab_ShowPoeticsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowPoeticsMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ šàçķš ôƒ Ñûţš.
        /// </summary>
        internal static string ObtainTab_ShowSacksOfNutsMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowSacksOfNutsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ ①ⓞⓞ šàçķš ôƒ Ñûţš·.
        /// </summary>
        internal static string ObtainTab_ShowSacksOfNutsMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowSacksOfNutsMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Ṽéñţûŕéš.
        /// </summary>
        internal static string ObtainTab_ShowVentureMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowVentureMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ à Ṽéñţûŕé·.
        /// </summary>
        internal static string ObtainTab_ShowVentureMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowVentureMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Ŵôļƒ Ṁàŕķš.
        /// </summary>
        internal static string ObtainTab_ShowWolfMarksMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowWolfMarksMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ôƀţàîñ ①،ⓞⓞⓞ Ŵôļƒ Ṁàŕķš·.
        /// </summary>
        internal static string ObtainTab_ShowWolfMarksMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowWolfMarksMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ &quot;Ýôû ŕôļļéð···&quot; ɱéššàĝéš.
        /// </summary>
        internal static string ObtainTab_ShowYouRolledMessages {
            get {
                return ResourceManager.GetString("ObtainTab_ShowYouRolledMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ ţĥé ɱéššàĝé ţĥàţ ôççûŕš àƒţéŕ éṽéŕýôñé ĥàš ŕôļļéð ôñ ļôôţ àñð ýôû àŕé ĝîṽéñ ţĥé ŕéšûļţ ôƒ ýôûŕ ŕôļļ·
        ///éĝ· Ýôû ŕôļļ Ñééð/Ĝŕééð ôñ ţĥé &lt;item&gt;· ⑥③¡.
        /// </summary>
        internal static string ObtainTab_ShowYouRolledMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ObtainTab_ShowYouRolledMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ƀôñûš àŵàŕðéð ƒôŕ ƀéîñĝ àñ àðṽéñţûŕéŕ îñ ñééð.
        /// </summary>
        internal static string ProgressTab_ShowAdventurerInNeedAwardMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowAdventurerInNeedAwardMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· À ƀôñûš ôƒ ⑦،②ⓞⓞ ĝîļ ĥàš ƀééñ àŵàŕðéð ƒôŕ ƀéîñĝ àñ àðṽéñţûŕéŕ îñ ñééð·.
        /// </summary>
        internal static string ProgressTab_ShowAdventurerInNeedAwardMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowAdventurerInNeedAwardMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ƀôñûš àŵàŕð ƒôŕ ûšîñĝ ðûţý ŕôûļéţţé.
        /// </summary>
        internal static string ProgressTab_ShowBonusAwardForDutyRouletteMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowBonusAwardForDutyRouletteMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· À ƀôñûš ôƒ ④،②⑤②،④⑨⑧ éẋþéŕîéñçé þôîñţš àñð ①②،ⓞⓞⓞ ĝîļ ĥàš ƀééñ àŵàŕðéð ƒôŕ ûšîñĝ ţĥé ðûţý ŕôûļéţţé·.
        /// </summary>
        internal static string ProgressTab_ShowBonusAwardForDutyRouletteMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowBonusAwardForDutyRouletteMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ éàŕñéð àçĥîéṽéɱéñţ ɱéššàĝéš.
        /// </summary>
        internal static string ProgressTab_ShowEarnedAchievementMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowEarnedAchievementMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ éẋþéŕîéñçé ĝàîñ ɱéššàĝéš.
        /// </summary>
        internal static string ProgressTab_ShowExperienceGainMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowExperienceGainMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ĝàîñ ②،③⑧⑧ Éẋþéŕîéñçé Þôîñţš·.
        /// </summary>
        internal static string ProgressTab_ShowExperienceGainMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowExperienceGainMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ļéàŕñéð àƀîļîţý ɱéššàĝéš.
        /// </summary>
        internal static string ProgressTab_ShowLearnedAbilityMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowLearnedAbilityMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ ţĥé ɱéššàĝé ţĥàţ ôççûŕš ŵĥéñ ýôû ļéàŕñ à ñéŵ àƀîļîţý·
        ///Îţ çàñ ƀé çôñšîðéŕéð šþàɱɱý îñ Þàļàçé ôƒ ţĥé Ðéàð àñð Ĥéàṽéñ Ôñ Ĥîĝĥ·.
        /// </summary>
        internal static string ProgressTab_ShowLearnedAbilityMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowLearnedAbilityMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ļéṽéļ ûþ ɱéššàĝéš.
        /// </summary>
        internal static string ProgressTab_ShowLevelUpMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowLevelUpMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ ţĥé ɱéššàĝé ţĥàţ ôççûŕš ŵĥéñ ýôû ļéṽéļ ûþ·
        ///Îţ çàñ ƀé çôñšîðéŕéð šþàɱɱý îñ Þàļàçé ôƒ ţĥé Ðéàð àñð Ĥéàṽéñ Ôñ Ĥîĝĥ·.
        /// </summary>
        internal static string ProgressTab_ShowLevelUpMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowLevelUpMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţĥîš ŵîļļ šĥôŵ ţĥé ɱéššàĝé ţĥàţ ôççûŕš ŵĥéñ ôţĥéŕš ļéṽéļ ûþ·
        /// éĝ· Þļàýéŕ àţţàîñš ļéṽéļ ③③¡.
        /// </summary>
        internal static string ProgressTab_ShowOtherPlayerLevelUpMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowOtherPlayerLevelUpMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ôţĥéŕ þļàýéŕ&apos;š éàŕñéð àçĥîéṽéɱéñţ ɱéššàĝéš.
        /// </summary>
        internal static string ProgressTab_ShowOtherPlayersEarnedAchievementMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowOtherPlayersEarnedAchievementMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ôţĥéŕ þļàýéŕ&apos;š ļéṽéļ ûþ ɱéššàĝéš.
        /// </summary>
        internal static string ProgressTab_ShowOtherPlayersLevelUpMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowOtherPlayersLevelUpMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ÞṼÞ ÉẊÞ ĝàîñ ɱéššàĝéš.
        /// </summary>
        internal static string ProgressTab_ShowPVPExpGainMessages {
            get {
                return ResourceManager.GetString("ProgressTab_ShowPVPExpGainMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû àçǫûîŕé ⑤ⓞⓞ ÞṽÞ ÉẊÞ·.
        /// </summary>
        internal static string ProgressTab_ShowPVPExpGainMessagesHelpMarker {
            get {
                return ResourceManager.GetString("ProgressTab_ShowPVPExpGainMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šàṽé àñð Çļôšé Çôñƒîĝ.
        /// </summary>
        internal static string SettingsTabFooter_SaveAndCloseButtonText {
            get {
                return ResourceManager.GetString("SettingsTabFooter_SaveAndCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šàṽé.
        /// </summary>
        internal static string SettingsTabFooter_SaveButtonText {
            get {
                return ResourceManager.GetString("SettingsTabFooter_SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šûþþôŕţ ôñ Ķô‐Ƒî.
        /// </summary>
        internal static string SettingsTabFooter_SupportOnKofiButtonText {
            get {
                return ResourceManager.GetString("SettingsTabFooter_SupportOnKofiButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ŵîķî Þàĝé.
        /// </summary>
        internal static string SettingsTabFooter_WikiPageButtonText {
            get {
                return ResourceManager.GetString("SettingsTabFooter_WikiPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éẋþéŕîɱéñţàļ Ƒéàţûŕé∶ Îñṽéŕšé ɱôðé.
        /// </summary>
        internal static string SystemTab_ExperimentalFeatureInverseMode {
            get {
                return ResourceManager.GetString("SystemTab_ExperimentalFeatureInverseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ñô ļôñĝéŕ ƀļôçķš Šýšţéɱ ɱéššàĝéš ƀý ðéƒàûļţ·
        ///Ĥîðé ƒîļţéŕš ƀéçôɱé Šĥôŵ ƒîļţéŕš àñð Šĥôŵ ƒîļţéŕš ƀéçôɱé Ĥîðé ƒîļţéŕš·.
        /// </summary>
        internal static string SystemTab_ExperimentalFeatureInverseModeHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ExperimentalFeatureInverseModeHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îƒ ýôû ĥàṽé éñàƀļéð Îñṽéŕšé ɱôðé ýôû àŕé ôñ ýôûŕ ôŵñ àñð ŵîļļ ñôţ ŕéçéîṽé àñý šûþþôŕţ·
        ///Îţ îš àššûɱéð ýôû ķñôŵ ŵĥàţ ýôû àŕé ðôîñĝ·.
        /// </summary>
        internal static string SystemTab_ExperimentalFeatureInverseModeWarningText {
            get {
                return ResourceManager.GetString("SystemTab_ExperimentalFeatureInverseModeWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé Àéţĥéŕ Çôɱþàšš ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_HideAetherCompassMessages {
            get {
                return ResourceManager.GetString("SystemTab_HideAetherCompassMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ţĥé çôɱþàšš ðéţéçţš à çûŕŕéñţ àþþŕôẋîɱàţéļý ①④③ ýàļɱš ţô ţĥé Ŵéšţ···.
        /// </summary>
        internal static string SystemTab_HideAetherCompassMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideAetherCompassMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé Àîŕšĥîþ ṽôýàĝé ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_HideAirshipVoyageMessages {
            get {
                return ResourceManager.GetString("SystemTab_HideAirshipVoyageMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· À ñéŵ éẋþļôŕàţôŕý ṽôýàĝé ðéšţîñàţîôñ···ĥàš ƀééñ ðîšçôṽéŕéð¡.
        /// </summary>
        internal static string SystemTab_HideAirshipVoyageMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideAirshipVoyageMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé Çôɱþļéţéð Ṽéñţûŕé.
        /// </summary>
        internal static string SystemTab_HideCompletedVenture {
            get {
                return ResourceManager.GetString("SystemTab_HideCompletedVenture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· ŔéţàîñéŕÑàɱé ĥàš çôɱþļéţéð à ṽéñţûŕé¡.
        /// </summary>
        internal static string SystemTab_HideCompletedVentureHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideCompletedVentureHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé /çôûñţðôŵñ ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_HideCountdownMessages {
            get {
                return ResourceManager.GetString("SystemTab_HideCountdownMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ɓàţţļé çôɱɱéñçîñĝ îñ ①⑧ šéçôñðš¡.
        /// </summary>
        internal static string SystemTab_HideCountdownMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideCountdownMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé /îñšţàñçé ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_HideInstanceMessage {
            get {
                return ResourceManager.GetString("SystemTab_HideInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû àŕé ñôŵ îñ ţĥé îñšţàñçéð àŕéà Ôļð Šĥàŕļàýàñ ·
        ///Çûŕŕéñţ îñšţàñçé çàñ ƀé çôñƒîŕɱéð àţ àñý ţîɱé ûšîñĝ ţĥé / îñšţàñçé ţéẋţ çôɱɱàñð·.
        /// </summary>
        internal static string SystemTab_HideInstanceMessageHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideInstanceMessageHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé &quot;Šéàŕçĥ ƒôŕ îţéɱš&quot; ŕéšûļţš ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_HideItemSearchResultsMessage {
            get {
                return ResourceManager.GetString("SystemTab_HideItemSearchResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· ① îţéɱ ƒôûñð îñ ţĥé ④ţĥ ţàƀ ôƒ ýôûŕ îñṽéñţôŕý·.
        /// </summary>
        internal static string SystemTab_HideItemSearchResultsMessageHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideItemSearchResultsMessageHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé /ŕéàðýçĥéçķ ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_HideReadycheckMessages {
            get {
                return ResourceManager.GetString("SystemTab_HideReadycheckMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ŕéàðý çĥéçķ çôɱþļéţé·.
        /// </summary>
        internal static string SystemTab_HideReadycheckMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideReadycheckMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé Ŕéçéîṽéð Çôɱɱéñðàţîôñš.
        /// </summary>
        internal static string SystemTab_HideReceivedCommendations {
            get {
                return ResourceManager.GetString("SystemTab_HideReceivedCommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ŕéçéîṽéð à þļàýéŕ çôɱɱéñðàţîôñ¡.
        /// </summary>
        internal static string SystemTab_HideReceivedCommendationsHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideReceivedCommendationsHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé ŕéɱîñðéŕš ôƒ ŵĥàţ ţô /šàý îñ çĥàţ ðûŕîñĝ ǫûéšţš·.
        /// </summary>
        internal static string SystemTab_HideSayReminder {
            get {
                return ResourceManager.GetString("SystemTab_HideSayReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ŵîţĥ ţĥé çĥàţ ɱôðé îñ Šàý، éñţéŕ à þĥŕàšé çôñţàîñîñĝ “Ţàţàŕû” àţ ţĥé ðéšţîñàţîôñ þôîñţ·.
        /// </summary>
        internal static string SystemTab_HideSayReminderHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideSayReminderHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé Šýšţéɱ ɱéššàĝéš Ţîðý Çĥàţ šĥôŵš ƀý ðéƒàûļţ.
        /// </summary>
        internal static string SystemTab_HideShownDefaultDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_HideShownDefaultDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé Š Ŕàñķ Ĥûñţ šþàŵñ àññôûñçéɱéñţ.
        /// </summary>
        internal static string SystemTab_HideSRankSpawnAnnouncement {
            get {
                return ResourceManager.GetString("SystemTab_HideSRankSpawnAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû šéñšé ţĥé þŕéšéñçé ôƒ à þôŵéŕƒûļ ɱàŕķ···.
        /// </summary>
        internal static string SystemTab_HideSRankSpawnAnnouncementHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideSRankSpawnAnnouncementHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé ŠŠ Ŕàñķ Ṁîñîôñ àññôûñçéɱéñţš.
        /// </summary>
        internal static string SystemTab_HideSSRankMinionSpawnAnnouncement {
            get {
                return ResourceManager.GetString("SystemTab_HideSSRankMinionSpawnAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ţĥé ɱîñîôñš ôƒ àñ éẋţŕàôŕðîñàŕîļý þôŵéŕƒûļ ɱàŕķ àŕé ôñ ţĥé ĥûñţ ƒôŕ þŕéý···
        ///Ţĥé ɱîñîôñš ôƒ àñ éẋţŕàôŕðîñàŕîļý þôŵéŕƒûļ ɱàŕķ ĥàṽé ŵîţĥðŕàŵñ···.
        /// </summary>
        internal static string SystemTab_HideSSRankMinionSpawnAnnouncementHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideSSRankMinionSpawnAnnouncementHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé Šûƀɱàŕîñé ṽôýàĝé ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_HideSubmarineVoyageMessages {
            get {
                return ResourceManager.GetString("SystemTab_HideSubmarineVoyageMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· À ñéŵ šûƀàǫûàţîç ṽôýàĝé ðéšţîñàţîôñ···ĥàš ƀééñ ðîšçôṽéŕéð¡.
        /// </summary>
        internal static string SystemTab_HideSubmarineVoyageMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideSubmarineVoyageMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé ţŕý ôñ ĝļàɱôûŕ ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_HideTryOnGlamourMessages {
            get {
                return ResourceManager.GetString("SystemTab_HideTryOnGlamourMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ţŕý ôñ îţéɱ·.
        /// </summary>
        internal static string SystemTab_HideTryOnGlamourMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideTryOnGlamourMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé ṽîšţà àŕŕîṽàļ àñð šţŕàý ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_HideVistaMessages {
            get {
                return ResourceManager.GetString("SystemTab_HideVistaMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû ĥàṽé àŕŕîṽéð àţ à ṽîšţà¡ àñð Ýôû ĥàṽé šţŕàýéð ţôô ƒàŕ ƒŕôɱ ţĥé ṽîšţà·.
        /// </summary>
        internal static string SystemTab_HideVistaMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideVistaMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ĥîðé &quot;Ýôû šéñšé šôɱéţĥîñĝ···&quot; ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_HideYouSenseSomethingMessages {
            get {
                return ResourceManager.GetString("SystemTab_HideYouSenseSomethingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû šéñšé šôɱéţĥîñĝ ţô ţĥé ƒàŕ، ƒàŕ šôûţĥŵéšţ···.
        /// </summary>
        internal static string SystemTab_HideYouSenseSomethingMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_HideYouSenseSomethingMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Þàŕţý ⅋ Îñṽîţé Ṁéššàĝéš.
        /// </summary>
        internal static string SystemTab_PartyAndInviteDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_PartyAndInviteDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÞÔŢÐ ⅋ ĤôĤ.
        /// </summary>
        internal static string SystemTab_POTDHoHDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_POTDHoHDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Àççûŕšéð Ĥôàŕð îš ðîšçôṽéŕéð.
        /// </summary>
        internal static string SystemTab_ShowAccursedHoardDiscoveredMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAccursedHoardDiscoveredMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Àççûŕšéð Ĥôàŕð îš ñôţ šéñšéð ôñ ţĥé çûŕŕéñţ ƒļôôŕ.
        /// </summary>
        internal static string SystemTab_ShowAccursedHoardNotSensedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAccursedHoardNotSensedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Àççûŕšéð Ĥôàŕð îš šéñšéð.
        /// </summary>
        internal static string SystemTab_ShowAccursedHoardSensedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAccursedHoardSensedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Àéţĥéŕþôôļ îñçŕéàšéš.
        /// </summary>
        internal static string SystemTab_ShowAetherpoolIncreasesMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAetherpoolIncreasesMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Àéţĥéŕþôôļ ŕéɱàîñš ûñçĥàñĝéð···.
        /// </summary>
        internal static string SystemTab_ShowAetherpoolRemainsUnchangedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAetherpoolRemainsUnchangedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ÀŔŔ Ŕéļîç ƀôôķ šţéþ çôɱþļéţéð ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_ShowARRRelicBookStepMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowARRRelicBookStepMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Àļļ ôƀĵéçţîṽéš ûñðéŕ ţĥé çàţéĝôŕý Ðûñĝéôñš ƒôŕ &lt;Relic Weapon&gt; ‐ Šţŕéñĝţĥ ⁺② çôɱþļéţé¡.
        /// </summary>
        internal static string SystemTab_ShowARRRelicBookStepMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowARRRelicBookStepMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ÀŔŔ Ŕéļîç ƀôôķ šţéþ þŕôĝŕéšš ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_ShowARRRelicProgressMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowARRRelicProgressMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ŕéçôŕð ôƒ Ôûŕàñôš ķîļļ (①/①) àððéð ƒôŕ &lt;Relic Weapon&gt; ‐ Šţŕéñĝţĥ ⁺②·.
        /// </summary>
        internal static string SystemTab_ShowARRRelicProgressMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowARRRelicProgressMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ &quot;Àŵàîţîñĝ ţŕàðé çôñƒîŕɱàţîôñ&quot; ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_ShowAwaitingTradeConfirmationMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowAwaitingTradeConfirmationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ ţĥé Çàîŕñ ôƒ Þàššàĝé îš àçţîṽàţéð.
        /// </summary>
        internal static string SystemTab_ShowCairnOfPassageActivatedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowCairnOfPassageActivatedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ ţĥé Çàîŕñ ôƒ Þàššàĝé ƀéĝîñš ţô ĝļôŵ.
        /// </summary>
        internal static string SystemTab_ShowCairnOfPassageGlowsMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowCairnOfPassageGlowsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Çàîŕñ ôƒ Ŕéţûŕñ îš ûšéð.
        /// </summary>
        internal static string SystemTab_ShowCairnOfReturnUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowCairnOfReturnUsedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ çôɱþļéţîôñ ţîɱé ŵĥéñ ûñŕéšţŕîçţéð þàŕţý îš àçţîṽé.
        /// </summary>
        internal static string SystemTab_ShowCompletionTimeForUnrestrictedParty {
            get {
                return ResourceManager.GetString("SystemTab_ShowCompletionTimeForUnrestrictedParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· &lt;Duty&gt; çôɱþļéţîôñ ţîɱé∶ ⓞⓞ∶③ⓞ.
        /// </summary>
        internal static string SystemTab_ShowCompletionTimeForUnrestrictedPartyHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowCompletionTimeForUnrestrictedPartyHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ þàŕţý ðîšƀàñðš àñð ðîššôļṽéš.
        /// </summary>
        internal static string SystemTab_ShowDisbandAndDissolveMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowDisbandAndDissolveMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ƒļôôŕ ñûɱƀéŕ ŵĥéñ éñţéŕîñĝ à ñéŵ ƒļôôŕ.
        /// </summary>
        internal static string SystemTab_ShowFloorNumberMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowFloorNumberMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ɱéššàĝé ŵĥéñ çĥàñĝîñĝ ĝéàŕšéţš.
        /// </summary>
        internal static string SystemTab_ShowGearsetChangingMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowGearsetChangingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///éĝ· “Ŕéð Ṁàĝé” éǫûîþþéð·.
        /// </summary>
        internal static string SystemTab_ShowGearsetChangingMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowGearsetChangingMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ɱéššàĝé ŵĥéñ çĥàñĝîñĝ ĝļàɱôûŕ þļàţéš.
        /// </summary>
        internal static string SystemTab_ShowGlamourPlateChangingMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowGlamourPlateChangingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///éĝ· Ĝļàɱôûŕš þŕôĵéçţéð ƒŕôɱ þļàţé ①ⓞ·.
        /// </summary>
        internal static string SystemTab_ShowGlamourPlateChangingMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowGlamourPlateChangingMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ Šýšţéɱ ɱéššàĝéš Ţîðý Çĥàţ ĥîðéš ƀý ðéƒàûļţ.
        /// </summary>
        internal static string SystemTab_ShowHiddenMessagesDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_ShowHiddenMessagesDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ĥûñţ ɱàŕķ šļàîñ ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_ShowHuntMarkSlainMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowHuntMarkSlainMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ĥûñţ ɱàŕķ &lt;mark&gt; šļàîñ¡ ①/③.
        /// </summary>
        internal static string SystemTab_ShowHuntMarkSlainMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowHuntMarkSlainMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ĵôîñéð þàŕţý/çŕôšš‐þàŕţý ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_ShowJoinedCrossworldPartyMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowJoinedCrossworldPartyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ þļàýéŕš ĵôîñîñĝ þàŕţý.
        /// </summary>
        internal static string SystemTab_ShowJoiningPartyMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowJoiningPartyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ þļàýéŕš ļéàṽîñĝ þàŕţý.
        /// </summary>
        internal static string SystemTab_ShowLeftPartyMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowLeftPartyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ îţéɱš àţţàçĥéð ţô šéñţ ɱàîļ.
        /// </summary>
        internal static string SystemTab_ShowMailAttachmentMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowMailAttachmentMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ýôû àţţàçĥ ② þôţš ôƒ Ðàļàɱûð Ŕéð Ðýé ţô ţĥé ļéţţéŕ·.
        /// </summary>
        internal static string SystemTab_ShowMailAttachmentMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowMailAttachmentMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ ţĥé þàŕţý ôƀţàîñš à þôɱàñðéŕ.
        /// </summary>
        internal static string SystemTab_ShowObtainedPomanderMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowObtainedPomanderMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ôñļîñé šţàţûš ûþðàţéš.
        /// </summary>
        internal static string SystemTab_ShowOnlineStatusMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowOnlineStatusMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ûþðàţîñĝ ôñļîñé šţàţûš ţô Àŵàý ƒŕôɱ Ķéýƀôàŕð·.
        /// </summary>
        internal static string SystemTab_ShowOnlineStatusMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowOnlineStatusMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Þôɱàñðéŕ ôƒ Àƒƒļûéñçé îš ûšéð.
        /// </summary>
        internal static string SystemTab_ShowPomanderOfAffluenceUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfAffluenceUsedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Þôɱàñðéŕ ôƒ Àļţéŕàţîôñ îš ûšéð.
        /// </summary>
        internal static string SystemTab_ShowPomanderOfAlterationUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfAlterationUsedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Þôɱàñðéŕ ôƒ Ƒļîĝĥţ îš ûšéð.
        /// </summary>
        internal static string SystemTab_ShowPomanderOfFlightUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfFlightUsedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Þôɱàñðéŕ ôƒ Šàƒéţý îš ûšéð.
        /// </summary>
        internal static string SystemTab_ShowPomanderOfSafetyUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfSafetyUsedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Þôɱàñðéŕ ôƒ Šéŕéñîţý îš ûšéð.
        /// </summary>
        internal static string SystemTab_ShowPomanderOfSerenityUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfSerenityUsedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Þôɱàñðéŕ ôƒ Šîĝĥţ îš ûšéð.
        /// </summary>
        internal static string SystemTab_ShowPomanderOfSightUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfSightUsedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ Þôɱàñðéŕ ôƒ Ŵîţçĥîñĝ îš ûšéð.
        /// </summary>
        internal static string SystemTab_ShowPomanderOfWitchingUsedMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowPomanderOfWitchingUsedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŕéçéîṽéð þàŕţý îñṽîţàţîôñš.
        /// </summary>
        internal static string SystemTab_ShowReceivedPartyInvitationMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowReceivedPartyInvitationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ŵĥéñ ýôû ŕéţûŕñ à þôɱàñðéŕ ţô ţĥé çôƒƒéŕ.
        /// </summary>
        internal static string SystemTab_ShowReturnedPomanderMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowReturnedPomanderMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ šéñţ þàŕţý îñṽîţéš.
        /// </summary>
        internal static string SystemTab_ShowSentPartyInviteMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowSentPartyInviteMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ţéļéþôŕţ ôƒƒéŕš ƒŕôɱ þàŕţý ɱéɱƀéŕš.
        /// </summary>
        internal static string SystemTab_ShowTeleportOfferFromPartyMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowTeleportOfferFromPartyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ &quot;Ţŕàðé çàñçéļéð·&quot; ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_ShowTradeCanceledMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowTradeCanceledMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ &quot;Ţŕàðé çôɱþļéţé·&quot; ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_ShowTradeCompleteMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowTradeCompleteMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ &quot;Ţŕàðé ŕéǫûéšţ šéñţ ţô&quot; ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_ShowTradeRequestSentMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowTradeRequestSentMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ţŕàñšƒéŕéñçé ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_ShowTransferenceMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowTransferenceMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ ṽôļûɱé çôñţŕôļ ɱéššàĝéš.
        /// </summary>
        internal static string SystemTab_ShowVolumeControlMessages {
            get {
                return ResourceManager.GetString("SystemTab_ShowVolumeControlMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éĝ· Ṁàšţéŕ Ṽôļûɱé ɱûţéð، ƁĜṀ ṽôļûɱé šéţ ţô ⑤ⓞ·.
        /// </summary>
        internal static string SystemTab_ShowVolumeControlMessagesHelpMarker {
            get {
                return ResourceManager.GetString("SystemTab_ShowVolumeControlMessagesHelpMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ţŕàðîñĝ Ṁéššàĝéš.
        /// </summary>
        internal static string SystemTab_TradingDropdownHeader {
            get {
                return ResourceManager.GetString("SystemTab_TradingDropdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ýôû ɱûšţ éñţéŕ ţĥé þļàýéŕ&apos;š ñàɱé àš îţ ŵôûļð ƀé šééñ îñ çĥàţ ‐ îñçļûðîñĝ àñý þéŕîôðš·
        ///
        ///éĝ·
        ///Šûŕñàɱé Àƀƀŕéṽîàţéð∶ Éẋàɱþļé Ñ·
        ///Ƒôŕéñàɱé Àƀƀŕéṽîàţéð∶ É· Ñàɱé
        ///Îñîţîàļš∶ É· Ñ·.
        /// </summary>
        internal static string WhitelistTab_ExactNameMatchWhitelistExplanation {
            get {
                return ResourceManager.GetString("WhitelistTab_ExactNameMatchWhitelistExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ûšéŕš àððéð ţô ţĥé ŵĥîţéļîšţ ŵîļļ ƀé ţŕéàţéð àš îƒ ţĥéý ŵéŕé ýôû ƒôŕ àļļ ƒîļţéŕ šéţţîñĝš·
        ///Éñţéŕ à þļàýéŕ&apos;š ƒîŕšţ àñð ļàšţ ñàɱé àñð ţĥéñ þŕéšš &lt;Enter&gt; ţô àðð ţĥéɱ ţô ţĥé ŵĥîţéļîšţ·.
        /// </summary>
        internal static string WhitelistTab_ExplanationMessage {
            get {
                return ResourceManager.GetString("WhitelistTab_ExplanationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Þļàýéŕ Îñƒôŕɱàţîôñ.
        /// </summary>
        internal static string WhitelistTab_PlayerInformationTableHeader {
            get {
                return ResourceManager.GetString("WhitelistTab_PlayerInformationTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šéļéçţ Çĥàññéļš.
        /// </summary>
        internal static string WhitelistTab_SelectChannelsHeader {
            get {
                return ResourceManager.GetString("WhitelistTab_SelectChannelsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ àļļ ɱéššàĝéš šéñţ ƀý ŵĥîţéļîšţéð þļàýéŕ.
        /// </summary>
        internal static string WhitelistTab_ShowAllMessagesByWhitelistedPlayer {
            get {
                return ResourceManager.GetString("WhitelistTab_ShowAllMessagesByWhitelistedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šĥôŵ àļļ ɱéššàĝéš ţàŕĝéţîñĝ à ŵĥîţéļîšţéð þļàýéŕ.
        /// </summary>
        internal static string WhitelistTab_ShowAllMessagesTargetingWhitelistedPlayer {
            get {
                return ResourceManager.GetString("WhitelistTab_ShowAllMessagesTargetingWhitelistedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ƒîŕšţ Ñàɱé∶ .
        /// </summary>
        internal static string WhitelistTab_WhitelistedPlayerFirstName {
            get {
                return ResourceManager.GetString("WhitelistTab_WhitelistedPlayerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ļàšţ Ñàɱé∶ .
        /// </summary>
        internal static string WhitelistTab_WhitelistedPlayerLastName {
            get {
                return ResourceManager.GetString("WhitelistTab_WhitelistedPlayerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šéŕṽéŕ Ñàɱé∶ .
        /// </summary>
        internal static string WhitelistTab_WhitelistedPlayerServerName {
            get {
                return ResourceManager.GetString("WhitelistTab_WhitelistedPlayerServerName", resourceCulture);
            }
        }
    }
}
