using System.Collections.Generic;

namespace TidyChat.Settings.Search;

/// <summary>
///     Maps configuration property names to exact Languages label keys used in settings tabs.
///     Prevents fuzzy search from pairing the wrong checkbox label with a setting.
/// </summary>
internal static class SettingsPropertyLabelKeys
{
    private static readonly Dictionary<string, string> ByPropertyName = new(StringComparer.Ordinal)
    {
        ["HideAdventurerInNeedBonus"] = nameof(Languages.ProgressTab_HideAdventurerInNeedAwardMessages),
        ["HideFateLevelSync"] = nameof(Languages.SystemTab_HideFateLevelSyncMessages),
        ["HideInventoryItemAdded"] = nameof(Languages.CurrenciesTab_HideInventoryItemAddedMessages),
        ["HideOrchestrionPlaying"] = nameof(Languages.SystemTab_HideOrchestrionPlaying),
        ["HideRouletteBonus"] = nameof(Languages.ProgressTab_HideBonusAwardForDutyRouletteMessages),
        ["HideObtainedAlliedSeals"] = nameof(Languages.CurrenciesTab_HideAlliedSealsMessages),
        ["HideObtainedCenturioSeals"] = nameof(Languages.CurrenciesTab_HideCenturioSealsMessages),
        ["HideObtainedGil"] = nameof(Languages.CurrenciesTab_HideGilMessages),
        ["HideObtainedNuts"] = nameof(Languages.CurrenciesTab_HideSacksOfNutsMessages),
        ["HideObtainedSeals"] = nameof(Languages.CurrenciesTab_HideGrandCompanySealsMessages),
        ["HideObtainedVenture"] = nameof(Languages.CurrenciesTab_HideVentureMessages),
        ["HideObtainedWolfMarks"] = nameof(Languages.CurrenciesTab_HideWolfMarksMessages),
        ["HideTomestoneWeeklyCap"] = nameof(Languages.CurrenciesTab_HideTomestoneWeeklyCapMessages),
        ["ShowGainExperience"] = nameof(Languages.ProgressTab_ShowExperienceGainMessages),
        ["ShowGainPvpExp"] = nameof(Languages.ProgressTab_ShowPvpExpGainMessages),
        ["ShowGainPvpRank"] = nameof(Languages.ProgressTab_ShowPvpRankMessages),
        ["ShowGainSeriesExp"] = nameof(Languages.ProgressTab_ShowSeriesProgressMessages),
        ["ShowPvpZoneAnnouncements"] = nameof(Languages.ProgressTab_ShowPvpZoneAnnouncements),
        ["ShowLevelUps"] = nameof(Languages.ProgressTab_ShowLevelUpMessages),
        ["ShowOtherLevelUps"] = nameof(Languages.ProgressTab_ShowOtherPlayersLevelUpMessages),
        ["ShowEarnAchievement"] = nameof(Languages.ProgressTab_ShowEarnedAchievementMessages),
        ["ShowOtherEarnedAchievement"] = nameof(Languages.ProgressTab_ShowOtherPlayersEarnedAchievementMessages),
        ["ShowAbilityUnlocks"] = nameof(Languages.ProgressTab_ShowLearnedAbilityMessages),
        ["ShowMountMessages"] = nameof(Languages.ProgressTab_ShowMountMessages),
        ["ShowQuestProgress"] = nameof(Languages.ProgressTab_ShowQuestProgressMessages),
        ["ShowFirstClearAward"] = nameof(Languages.ProgressTab_ShowFirstClearAward),
        ["ShowSecondChanceAward"] = nameof(Languages.ProgressTab_ShowSecondChanceAward),

        ["ShowCombatCasting"] = nameof(Languages.CombatTab_ShowCombatCastingMessages),
        ["ShowCombatAbilities"] = nameof(Languages.CombatTab_ShowCombatAbilitiesMessages),
        ["ShowCombatDamage"] = nameof(Languages.CombatTab_ShowCombatDamageMessages),
        ["ShowCombatMisses"] = nameof(Languages.CombatTab_ShowCombatMissesMessages),
        ["ShowCombatHealing"] = nameof(Languages.CombatTab_ShowCombatHealingMessages),
        ["ShowCombatEffects"] = nameof(Languages.CombatTab_ShowCombatEffectsMessages),
        ["ShowCombatDefeat"] = nameof(Languages.CombatTab_ShowCombatDefeatMessages),
        ["ShowCombatEnemyReady"] = nameof(Languages.CombatTab_ShowCombatEnemyReadyMessages),
        ["ShowCombatAdds"] = nameof(Languages.CombatTab_ShowCombatAddsMessages),
        ["ShowCombatEnmity"] = nameof(Languages.CombatTab_ShowCombatEnmityMessages),
        ["ShowObtainedItems"] = nameof(Languages.CurrenciesTab_ShowGeneralItemObtains),
        ["ShowObtainedQuestItems"] = nameof(Languages.CurrenciesTab_ShowObtainedQuestItems),

        ["HideObtainedMaterials"] = nameof(Languages.AlliedSocietiesTab_HideBeastTribeCraftingMaterialsMessages),
        ["HideObtainedTribalCurrency"] = nameof(Languages.AlliedSocietiesTab_HideBeastTribeCurrenciesMessages),

        ["ShowDutyFinder"] = nameof(Languages.DutyTab_ShowDutyFinderMessages),
        ["ShowCompletionTime"] = nameof(Languages.DutyTab_ShowCompletionTimeForUnrestrictedParty),

        ["HideObtainedMGP"] = nameof(Languages.GoldSaucerTab_HideMGPMessages),
        ["ShowGoldSaucerSwingMinigames"] = nameof(Languages.GoldSaucerTab_ShowSwingMinigames),
        ["ShowTripleTriadAllowed"] = nameof(Languages.GoldSaucerTab_ShowTripleTriadAllowed),
        ["ShowTripleTriadNotAllowed"] = nameof(Languages.GoldSaucerTab_ShowTripleTriadNotAllowed),

        ["ShowEligibleForCoffers"] = nameof(Languages.SystemTab_ShowNumberOfCoffers),
        ["ShowGearDyeApplied"] = nameof(Languages.SystemTab_ShowGearDyeApplied),
        ["ShowGearItemsRepaired"] = nameof(Languages.SystemTab_ShowGearItemsRepaired),
        ["ShowGearsetEquipped"] = nameof(Languages.SystemTab_ShowGearsetChangingMessages),
        ["ShowGearsetGlamourRestoreFailed"] = nameof(Languages.SystemTab_ShowGearsetGlamourRestoreFailed),
        ["ShowGlamourAltered"] = nameof(Languages.SystemTab_ShowGlamourAltered),
        ["ShowGlamourPlatePartialApply"] = nameof(Languages.SystemTab_ShowGlamourPlatePartialApply),
        ["ShowGlamourPlateProjected"] = nameof(Languages.SystemTab_ShowGlamourPlateProjected),
        ["ShowJobChange"] = nameof(Languages.SystemTab_ShowJobChangeMessages),
        ["ShowPortraitMessages"] = nameof(Languages.SystemTab_ShowPortraitMessages),
        ["ShowSpiritboundGear"] = nameof(Languages.SystemTab_ShowSpiritboundMessages),
        ["ShowTryOnGlamour"] = nameof(Languages.SystemTab_ShowTryOnGlamourMessages),
        ["ShowTryOnGlamourCast"] = nameof(Languages.SystemTab_ShowTryOnGlamourCast),

        ["ShowCastLot"] = nameof(Languages.PartyTab_CastYourLotMessages),
        ["ShowCountdownTime"] = nameof(Languages.PartyTab_ShowCountdownMessages),
        ["ShowInvitedBy"] = nameof(Languages.PartyTab_ShowReceivedPartyInvitationMessages),
        ["ShowInviteeJoins"] = nameof(Languages.PartyTab_ShowJoiningPartyMessages),
        ["ShowInviteSent"] = nameof(Languages.PartyTab_ShowSentPartyInviteMessages),
        ["ShowJoinParty"] = nameof(Languages.PartyTab_ShowJoinedCrossworldPartyMessages),
        ["ShowLeftParty"] = nameof(Languages.PartyTab_ShowLeftPartyMessages),
        ["ShowLootRoll"] = nameof(Languages.PartyTab_ShowYouRolledMessages),
        ["ShowNowLeaderOf"] = nameof(Languages.PartyTab_ShowNowALeader),
        ["ShowOfferedTeleport"] = nameof(Languages.PartyTab_ShowTeleportOfferFromPartyMessages),
        ["ShowOnlyPartyMemberRolls"] = nameof(Languages.PartyTab_ShowOnlyPartyMemberRolls),
        ["ShowOthersCastLot"] = nameof(Languages.PartyTab_ShowAnotherPlayerCastsLotMessages),
        ["ShowOthersLootRoll"] = nameof(Languages.PartyTab_ShowAnotherPlayerRollsMessages),
        ["ShowPartyDisband"] = nameof(Languages.PartyTab_ShowDisbandAndDissolveMessages),
        ["ShowPartyDissolved"] = nameof(Languages.PartyTab_ShowDisbandAndDissolveMessages),
        ["ShowPartyInformation"] = nameof(Languages.PartyTab_ShowPartyObjectiveOnJoin),
        ["ShowReadyChecks"] = nameof(Languages.PartyTab_ShowReadycheckMessages),
        ["ShowSealedOff"] = nameof(Languages.PartyTab_ShowSealedOffMessages),
        ["HideOthersObtain"] = nameof(Languages.PartyTab_HideAnotherPlayerObtainsItemMessages),

        ["ShowAetherialReductionMinigame"] = nameof(Languages.GatheringTab_ShowAetherialReductionMinigameMessages),
        ["ShowAetherialReductionSands"] = nameof(Languages.GatheringTab_ShowObtainedSandsFromAetherialReductionMessages),
        ["ShowAetherialReductionSuccess"] = nameof(Languages.GatheringTab_ShowAetherialReductionSuccessMessages),
        ["ShowAllOtherGathering"] = nameof(Languages.GatheringTab_ShowAllOtherGathering),
        ["ShowGatherersBoon"] = nameof(Languages.GatheringTab_HideGatheringBoonLocationMessages),
        ["ShowGatheringAttempts"] = nameof(Languages.GatheringTab_HideGatheringAttemptsLocationMessages),
        ["ShowGatheringBuffEffectGain"] = nameof(Languages.GatheringTab_ShowGatheringBuffEffectGain),
        ["ShowGatheringCollectableObtains"] = nameof(Languages.GatheringTab_ShowGatheringCollectableObtainMessages),
        ["ShowGatheringSenses"] = nameof(Languages.GatheringTab_ShowGatheringSensesLabel),
        ["ShowGatheringStartEnd"] = nameof(Languages.GatheringTab_ShowGatheringStartEnd),
        ["ShowGatheringYield"] = nameof(Languages.GatheringTab_HideGatheringYieldLocationMessages),
        ["ShowLocationAffects"] = nameof(Languages.GatheringTab_ShowLocationGatheringEffectMessages),
        ["HideObtainedShards"] = nameof(Languages.GatheringTab_HideElementalShardsCrystalsClustersMessages),

        ["ShowCaughtFish"] = nameof(Languages.GatheringTab_ShowFishAddedToGuideMessages),
        ["ShowCurrentFishingHole"] = nameof(Languages.GatheringTab_ShowFishingHoleName),
        ["ShowDiscoveredFishingHole"] = nameof(Languages.GatheringTab_ShowFishingHoleDiscovered),
        ["ShowFishingFlavorText"] = nameof(Languages.GatheringTab_ShowFishingFlavorText),
        ["ShowLureMessages"] = nameof(Languages.GatheringTab_ShowLureMessages),
        ["ShowMeasuringIlms"] = nameof(Languages.GatheringTab_ShowFishSizeMessages),
        ["ShowMooching"] = nameof(Languages.GatheringTab_ShowMooching),

        ["ShowCosmicClassPointsAndDataset"] = nameof(Languages.GatheringTab_ShowCosmicClassPointsAndDataset),
        ["ShowCosmicContainers"] = nameof(Languages.GatheringTab_ShowCosmicContainers),
        ["ShowCosmicDailyProgress"] = nameof(Languages.GatheringTab_ShowCosmicDailyProgress),
        ["ShowCosmicExplorationMessages"] = nameof(Languages.GatheringTab_ShowCosmicExplorationMessages),
        ["ShowCosmicRewards"] = nameof(Languages.GatheringTab_ShowCosmicRewards),
        ["ShowStellarAbleToExecute"] = nameof(Languages.GatheringTab_ShowStellarAbleToExecute),
        ["ShowStellarBuffEffectGain"] = nameof(Languages.GatheringTab_ShowStellarBuffEffectGain),
        ["ShowStellarMissionMessages"] = nameof(Languages.GatheringTab_ShowStellarMissionMessages),

        ["ShowCompletedVenture"] = nameof(Languages.EconomyTab_ShowCompletedVenture),
        ["ShowMarketGilEntrustedToRetainer"] = nameof(Languages.EconomyTab_ShowMarketGilEntrustedToRetainer),
        ["ShowRetainerVentureMessages"] = nameof(Languages.EconomyTab_ShowRetainerVentureMessages),

        ["ShowExploratoryVoyage"] = nameof(Languages.FreeCompanyTab_ShowAirshipVoyageMessages),
        ["ShowFreeCompanyMessageBook"] = nameof(Languages.FreeCompanyTab_ShowFreeCompanyMessageBookMessages),
        ["ShowSubaquaticVoyage"] = nameof(Languages.FreeCompanyTab_ShowSubmarineVoyageMessages),
        ["ShowSubaquaticVoyageEmbarked"] = nameof(Languages.FreeCompanyTab_ShowSubaquaticVoyageEmbarked),
        ["ShowSubaquaticVoyageFinalized"] = nameof(Languages.FreeCompanyTab_ShowSubaquaticVoyageFinalized),
        ["ShowSubaquaticVoyageOtherFinalized"] = nameof(Languages.FreeCompanyTab_ShowSubaquaticVoyageOtherFinalized),
        ["ShowSubaquaticVoyageReturned"] = nameof(Languages.FreeCompanyTab_ShowSubaquaticVoyageReturned),
        ["ShowSubmarineAttainsRank"] = nameof(Languages.FreeCompanyTab_ShowSubmarineAttainsRank),
        ["ShowSubmarinePartRepaired"] = nameof(Languages.FreeCompanyTab_ShowSubmarinePartRepaired),
        ["ShowSubmarineRetrievalLevelsIncreased"] =
            nameof(Languages.FreeCompanyTab_ShowSubmarineRetrievalLevelsIncreased),
        ["ShowUserLogins"] = nameof(Languages.FreeCompanyTab_ShowLoginMessages),
        ["ShowUserLogouts"] = nameof(Languages.FreeCompanyTab_ShowLogoutMessages),

        ["ShowCommendations"] = nameof(Languages.SystemTab_ShowReceivedCommendations),
        ["ShowInstanceMessage"] = nameof(Languages.SystemTab_ShowInstanceMessage),
        ["ShowAttachToMail"] = nameof(Languages.SystemTab_ShowMailAttachmentMessages),
        ["ShowRelicBookComplete"] = nameof(Languages.SystemTab_ShowARRRelicBookStepMessages),
        ["ShowRelicBookStep"] = nameof(Languages.SystemTab_ShowARRRelicProgressMessages),
        ["ShowOnlineStatus"] = nameof(Languages.SystemTab_ShowOnlineStatusMessages),
        ["ShowSearchForItemResults"] = nameof(Languages.SystemTab_ShowItemSearchResultsMessage),
        ["ShowItemSearchResults"] = nameof(Languages.SystemTab_ShowInventoryItemSearchResults),
        ["ShowLocationSearchResults"] = nameof(Languages.SystemTab_ShowLocationSearchResults),
        ["ShowPersonalMessageBook"] = nameof(Languages.SystemTab_ShowPersonalMessageBookMessages),
        ["HideObtainedClusters"] = nameof(Languages.SystemTab_HideCrackedClustersMessages),
        ["ShowAetheryteTicket"] = nameof(Languages.SystemTab_ShowAetheryteTicketMessage),
        ["ShowAttuneAetheryte"] = nameof(Languages.SystemTab_ShowAttuneAetheryteMessage),

        ["ShowSRankHunt"] = nameof(Languages.SystemTab_ShowSRankSpawnAnnouncement),
        ["ShowSSRankHunt"] = nameof(Languages.SystemTab_ShowSSRankMinionSpawnAnnouncement),
        ["ShowHuntSlain"] = nameof(Languages.SystemTab_ShowHuntMarkSlainMessages),
        ["ShowQuestReminder"] = nameof(Languages.SystemTab_ShowSayReminder),
        ["ShowSpideySenses"] = nameof(Languages.SystemTab_ShowYouSenseSomethingMessages),
        ["ShowLocationDiscovered"] = nameof(Languages.SystemTab_ShowLocationDiscoveredMessages),
        ["ShowHostilePresence"] = nameof(Languages.SystemTab_ShowHostilePresenceMessages),
        ["ShowAetherCompass"] = nameof(Languages.SystemTab_ShowAetherCompassMessages),
        ["ShowVistaMessages"] = nameof(Languages.SystemTab_ShowVistaMessages),

        ["ShowCraftingSynthesisComplete"] = nameof(Languages.CraftingTab_ShowCraftingSynthesisComplete),
        ["ShowTrialMessages"] = nameof(Languages.CraftingTab_ShowTrialSynthesisMessages),
        ["ShowOtherSynthesis"] = nameof(Languages.CraftingTab_ShowOtherPlayerCompletedSynthesisMessages),
        ["ShowAllOtherCrafting"] = nameof(Languages.CraftingTab_ShowAllOtherCrafting),
        ["ShowCraftingBuffEffectGain"] = nameof(Languages.CraftingTab_ShowCraftingBuffEffectGain),
        ["ShowCraftingAbleToExecute"] = nameof(Languages.CraftingTab_ShowCraftingAbleToExecute),

        ["FilterSystemMessages"] = nameof(Languages.GeneralTab_FilterSystemSpam),
        ["FilterProgressSpam"] = nameof(Languages.GeneralTab_FilterProgressSpam),
        ["FilterLootSpam"] = nameof(Languages.GeneralTab_FilterLootSpam),
        ["FilterObtainedSpam"] = nameof(Languages.GeneralTab_FilterObtainedSpam),
        ["FilterCraftingSpam"] = nameof(Languages.GeneralTab_FilterCraftingSpam),
        ["FilterGatheringSpam"] = nameof(Languages.GeneralTab_FilterGatheringSpam),
        ["FilterEmoteChannel"] = nameof(Languages.EmotesTab_FilterStandardEmotes),
        ["FilterCustomEmoteChannel"] = nameof(Languages.EmotesTab_FilterCustomEmoteChannel),

        ["IncludeChatTag"] = nameof(Languages.GeneralTab_TidyChatTag),
        ["EnableSmolMode"] = nameof(Languages.EnableTinyChat),
        ["NormalizeBlocks"] = nameof(Languages.NormalizeSpecialCharactersExceptInPartyOrAllianceChannels),
        ["AlwaysNormalizeBlocks"] = nameof(Languages.AlwaysNormalizeSpecialCharacters),
        ["BetterInstanceMessage"] = nameof(Languages.GeneralTab_ImprovedInstanceMessaging),
        ["BetterDutyCommenceMessage"] = nameof(Languages.GeneralTab_ImprovedDutyCommenceMessaging),
        ["InstanceInDtrBar"] = nameof(Languages.GeneralTab_InstanceInDTRBar),
        ["BetterCommendationMessage"] = nameof(Languages.GeneralTab_ImprovedPlayerCommendations),
        ["IncludeDutyNameInComms"] = nameof(Languages.GeneralTab_ImprovedCommendationsDutyName),
        ["BetterSayReminder"] = nameof(Languages.GeneralTab_ImprovedSayMessages),
        ["CopyBetterSayReminder"] = nameof(Languages.GeneralTab_CopySayMessage),
        ["BetterNoviceNetworkMessage"] = nameof(Languages.GeneralTab_ImprovedNoviceNetworkMessages),
        ["BetterTreasureDungeonMessage"] = nameof(Languages.GeneralTab_ImprovedTreasureDungeonMessages),
        ["BetterMarketBoardSaleMessage"] = nameof(Languages.GeneralTab_ImprovedMarketBoardSale),

        ["EnableDebugMode"] = nameof(Languages.ToolsTab_EnableDebugMode),
        ["DebugIncludeChannel"] = nameof(Languages.ToolsTab_DebugIncludeChannel),
        ["ChatHistoryFilter"] = nameof(Languages.ChatHistoryTab_EnableChatHistoryFilter),
        ["DisableSelfChatHistory"] = nameof(Languages.ChatHistoryTab_IgnoreMessagesSentByPlayer),
        ["SentByWhitelistPlayer"] = nameof(Languages.WhitelistTab_ShowAllMessagesByWhitelistedPlayer),
        ["TargetingWhitelistPlayer"] = nameof(Languages.WhitelistTab_ShowAllMessagesTargetingWhitelistedPlayer),

        ["ShowVendorSellMessages"] = nameof(Languages.EconomyTab_ShowVendorSellMessages),
        ["ShowVendorPurchaseMessages"] = nameof(Languages.EconomyTab_ShowVendorPurchaseMessages),
        ["ShowMarketBoardMessages"] = nameof(Languages.EconomyTab_ShowMarketBoardMessages),
        ["ShowMarketItemSold"] = nameof(Languages.EconomyTab_ShowMarketItemSold),
        ["ShowMarketAllItemsSold"] = nameof(Languages.EconomyTab_ShowMarketAllItemsSold),
        ["ShowMarketBoardSellingStatus"] = nameof(Languages.EconomyTab_ShowMarketBoardSellingStatus),
        ["ShowGilWithdrawnMessage"] = nameof(Languages.EconomyTab_ShowGilWithdrawnMessage),
        ["ShowGilSpentMessage"] = nameof(Languages.EconomyTab_ShowGilSpentMessage),
        ["ShowTradeSent"] = nameof(Languages.EconomyTab_ShowTradeRequestSent),
        ["ShowTradeCanceled"] = nameof(Languages.EconomyTab_ShowTradeCanceled),
        ["ShowAwaitingTradeConfirmation"] = nameof(Languages.EconomyTab_ShowTradeAwaitingConfirmation),
        ["ShowTradeComplete"] = nameof(Languages.EconomyTab_ShowTradeComplete),

        ["ShowObtainedPomander"] = nameof(Languages.DeepDungeonsTab_ShowObtainedPomanderMessages),
        ["ShowTrapTriggered"] = nameof(Languages.DeepDungeonsTab_ShowTrapTriggeredMessages),
        ["ShowCairnGlows"] = nameof(Languages.DeepDungeonsTab_ShowCairnOfPassageGlowsMessages),
        ["ShowRestoresLifeToFallen"] = nameof(Languages.DeepDungeonsTab_ShowCairnOfReturnUsedMessages),
        ["ShowCairnActivates"] = nameof(Languages.DeepDungeonsTab_ShowCairnOfPassageActivatedMessages),
        ["ShowTransference"] = nameof(Languages.DeepDungeonsTab_ShowTransferenceMessages),
        ["ShowAetherpoolIncrease"] = nameof(Languages.DeepDungeonsTab_ShowAetherpoolIncreasesMessages),
        ["ShowAetherpoolUnchanged"] = nameof(Languages.DeepDungeonsTab_ShowAetherpoolRemainsUnchangedMessages),
        ["ShowPomanderEffects"] = nameof(Languages.DeepDungeonsTab_ShowPomanderEffectsMessages),
        ["ShowFloorNumber"] = nameof(Languages.DeepDungeonsTab_ShowFloorNumberMessages),
        ["ShowSenseAccursedHoard"] = nameof(Languages.DeepDungeonsTab_ShowAccursedHoardSensedMessages),
        ["ShowDoNotSenseAccursedHoard"] = nameof(Languages.DeepDungeonsTab_ShowAccursedHoardNotSensedMessages),
        ["ShowDiscoverAccursedHoard"] = nameof(Languages.DeepDungeonsTab_ShowAccursedHoardDiscoveredMessages),

        ["ShowAttachedMateria"] = nameof(Languages.MateriaTab_ShowMateriaSuccesfullyAttachedMessages),
        ["ShowOvermeldFailure"] = nameof(Languages.MateriaTab_ShowMateriaOvermeldFailuresMessages),
        ["ShowMateriaShatters"] = nameof(Languages.MateriaTab_ShowMateriaShattersMessages),
        ["ShowMateriaExtract"] = nameof(Languages.MateriaTab_ShowMateriaExtractedMessages),
        ["ShowMateriaRetrieved"] = nameof(Languages.MateriaTab_ShowSuccesfullyRetrievedMateriaMessages),

        ["ShowDesynthesisLevel"] = nameof(Languages.DesynthesisTab_ShowDesynthesisLevelIncreasesMessages),
        ["ShowDesynthedItem"] = nameof(Languages.DesynthesisTab_ShowItemBeingDesynthesized),
        ["ShowDesynthesisObtains"] = nameof(Languages.DesynthesisTab_ShowObtainedItemsFromDesynthesisMessages),

        ["ShowInstancedAreaMessages"] = nameof(Languages.SystemTab_ShowInstancedAreaMessages),
        ["ShowDutyEndedMessage"] = nameof(Languages.SystemTab_ShowDutyEndedMessage),
        ["ShowGuildhestEndedMessage"] = nameof(Languages.SystemTab_ShowGuildhestEndedMessage),
        ["ShowLevelNoLongerSynced"] = nameof(Languages.SystemTab_ShowLevelNoLongerSynced),
        ["ShowDutyMechanicMessages"] = nameof(Languages.SystemTab_ShowDutyMechanicMessages),
        ["ShowDutyObjectiveBonus"] = nameof(Languages.SystemTab_ShowDutyObjectiveBonus),
        ["ShowEverythingElse"] = nameof(Languages.SystemTab_ShowEverythingElse),
        ["ShowChangesDiscarded"] = nameof(Languages.SystemTab_ShowChangesDiscarded),
        ["ShowChangesLost"] = nameof(Languages.SystemTab_ShowChangesLost),
        ["ShowActiveHelpEntry"] = nameof(Languages.SystemTab_ShowActiveHelpEntryMessages),
        ["ShowSanctuaryMessage"] = nameof(Languages.SystemTab_ShowSanctuaryMessage),
        ["ShowHousingWardMessage"] = nameof(Languages.SystemTab_ShowHousingWardMessage),

        ["ShowSelfUsedEmotes"] = nameof(Languages.EmotesTab_ShowSelfCustomEmotes),
        ["ShowOtherCustomEmotes"] = nameof(Languages.EmotesTab_ShowOtherCustomEmotes),
    };

    public static string? TryGet(string propertyName) =>
        ByPropertyName.GetValueOrDefault(propertyName);
}
